### ISSUE TITLE
Device name not updating on Android

### ISSUE THREAD

**Issue by soyangel** [PhilipsHue/flutter_reactive_ble#105]
**Describe the bug**
BLE Devices changes its name but the name in not changed on the data returned on scan. 

**To Reproduce**
Try scanning a device that changes its name on the advertising data but then on the scan results the name is not changed.

To fix this you can change ReactiveBleClient.kt:

```
                 .map { result ->
-                    ScanInfo(result.bleDevice.macAddress, result.bleDevice.name
+                    ScanInfo(result.bleDevice.macAddress, result.scanRecord.deviceName
                             ?: "",
                             result.rssi,
                             result.scanRecord.serviceData.mapKeys { it.key.uuid },
```

**Expected behavior**
Device name changes on scan results.

**Smartphone / tablet**
 - Device: Pixel 3a
 - OS: Android 10

**Peripheral device**
- Vendor, model: Custom
- Does it run a custom firmware / software: yes

**Additional context**

**Comment by werediver** [comment]
Relates to #83 (same issue on iOS, fixed).

**Comment by remonh87** [comment]
Will be available in coming release thanks for reporting!
