### ISSUE TITLE
How to stop Scanning to devices?  (Or how to stop the scanForDevices stream?)

### ISSUE THREAD

**Issue by 0100101101001011** [PhilipsHue/flutter_reactive_ble#113]
I'm quite new to flutter. I'm wondering how to stop scanning for peripheral after getting a list of devices?  

**To Reproduce**
`FlutterReactiveBle _ble = FlutterReactiveBle();

    _ble.statusStream.listen((status) {
      //code for handling status update
      print(status);
    });

    print(_ble.status);

    void startScan() {
      _ble.scanForDevices(withServices: [], scanMode: ScanMode.lowLatency, requireLocationServicesEnabled: true).listen((device) {
        //code for handling results
        print(
            'ID:' + device.id + 'Name:' + device.name
        );
        print(device.rssi);
      }, onError: (handleError) {
        //code for handling error
        print(handleError);
      });
    }`

**Comment by werediver** [comment]
To stop a scan (as well as to close an established connection) you need to unsubscribe from the corresponding stream.

You're creating a "subscription" object by calling [listen(⋯)](https://api.flutter.dev/flutter/dart-async/Stream/listen.html) method. Later you can [cancel()](https://api.flutter.dev/flutter/dart-async/StreamSubscription/cancel.html) this subscription.

**Comment by 0100101101001011** [comment]
Thank you very much! BTW, this library is amazing!
