### ISSUE TITLE
Question: reconnection to device after reboot.

### ISSUE THREAD

**Issue by iJamesPHP** [PhilipsHue/flutter_reactive_ble#136]
How should connecting to a device after it reboots be handled best? My solution of just connecting in the disconnect listener works fine on iOS. However, on Android it doesn't reconnect quick enough to capture the data I need (within 10 sec of reboot). Is there something I'm missing? Is stopping the scan crucial to anything working well on Android?

**Comment by remonh87** [comment]
@iJamesPHP connecting while scanning on Android is not recommended. You should first stop scanning and then try to connect. For more info about ble on Android and some more behaviour see: https://bit.ly/2HXddK1. Btw our library already works around a lot of these known issues.

Regarding the time, 10 seconds is quite long can you provide me the code that you are using?

**Comment by remonh87** [comment]
close the ticket for now feel free to reopen
