### ISSUE TITLE
Support iOS 13 in the example app

### ISSUE THREAD

**Issue by werediver** [PhilipsHue/flutter_reactive_ble#14]
As reported in [the issue 12](https://github.com/PhilipsHue/flutter_reactive_ble/issues/12#issuecomment-586193161), the example app needs some updates to "Info.plist" to properly work on iOS 13.

Specifically check `NSBluetoothAlwaysUsageDescription` and `NSBluetoothPeripheralUsageDescription` parameters.

**Comment by diegoveloper** [comment]
hello, any of the authors of this package are here? I was trying to reach this email `philipshuedev@gmail.com` but I didn't get any answer.

**Comment by werediver** [comment]
@diegoveloper The authors are here, me and @remonh87 are the creators and major contributors of the library, but what's your _actual_ question?

Sorry for the "philipshuedev" e-mail. I guess, it's a functional account that we personally do not monitor. I'll see what can be done to improve on this.

**Comment by diegoveloper** [comment]
Could you send me your mail?

**Comment by werediver** [comment]
@diegoveloper I'd find a separate ticket more appropriate for this discussion. Address your letters to raman.fedaseyeu at gmail.com to reach me.

@remonh87 I'll make sure you're in touch anyway, but check this out.
