### ISSUE TITLE
Improve consistency of error handling

### ISSUE THREAD

**Issue by remonh87** [PhilipsHue/flutter_reactive_ble#152]
In #151  we have an example of not useful adding of a stacktrace in the ble library. Let's walkthorugh the code and fix it consistently

**Comment by werediver** [comment]
I am not convinced that stack traces are not useful. Imagine a ticket here _with_ and _without_ a stack-trace. Which one would be easier to analyze?

**Comment by werediver** [comment]
It is (was) not useful there, because it is (was) not readable (not serialized to text), right? My point is about a readable stack-trace, obviously 😄

**Comment by remonh87** [comment]
Yes indeed my idea is to make the stacktrace either readable or remove it everywhere
