### ISSUE TITLE
Getting BLE Device UUID on Android.

### ISSUE THREAD

**Issue by 0100101101001011** [PhilipsHue/flutter_reactive_ble#155]
**Describe the problem**
This documentation says that "_For the required id parameter use a device ID retrieved through device discovery. On iOS the device ID is a UUID and on Android it is a MAC address_"

Is there a way to get the UUID on Android? As I am trying to store the same BLE device data with one consistent device ID across different devices.

**Comment by werediver** [comment]
That is not possible. The UUID of a BLE peripheral on iOS is _randomized_. If you (manually) remove pairing with a peripheral, next time it will be discovered with a new UUID. If a peripheral doesn't require pairing, the UUID may be randomized on discovery. Android can randomize the peripheral identifiers as well, even though that doesn't happen normally.

If you need to consistently identify a peripheral across iOS and Android, you should seek another way to do it. Perhaps, you can read some internal identifier specific to your device.
