### ISSUE TITLE
WriteCharacteristicWithResponse returns void

### ISSUE THREAD

**Issue by realrk69** [PhilipsHue/flutter_reactive_ble#160]
I think this is a bug:

```
final characteristic = QualifiedCharacteristic(serviceId: serviceUuid, characteristicId: characteristicUuid, deviceId: foundDeviceId);
final response = await _ble.writeCharacteristicWithResponse(characteristic, value: [0x00]);
```
It says the response is void and hence cannot be printed. What's wrong here?
In the documentation, it says the response is a List<int>

Also, my device takes very long, like really long to connect, but not all the time, sometimes it just works. Have tried restarting app, device and Android Studio, and none of these seem to be the problem. When it takes long to connect, this is what the log shows:
```
D/BluetoothGatt(23984): connect() - device: B8:27:EB:98:60:9B, auto: true
D/BluetoothGatt(23984): registerApp()
D/BluetoothGatt(23984): registerApp() - UUID=dc19fad4-a153-4f8f-8325-3198d2f4a91b
D/BluetoothGatt(23984): onClientRegistered() - status=0 clientIf=8
```
Stays like this with no new log till up to 7 minutes after which the device connects and starts discovering services. But the next time, it won't take as long. Anyone know about this? This also happens while connecting in your example app.

**Comment by remonh87** [comment]
The `List<int>` is a mistake in the readme which I will fix. Write with acknowledge just awaits a response for the device and that is it. The response is just an acknowledge call. BLE does not have a request response mechanism implemented like for example HTTP. See also #150  for a more elaborative answer.

**Comment by werediver** [comment]
See also #160, exactly the same confusion.

**Comment by realrk69** [comment]
What about the very long connect duration? It doesn't happen always...

**Comment by werediver** [comment]
That is unfortunate you're mixing two separate issues in one ticket.

You're using an Android device and they are known to exhibit very different BLE stack performance depending on their vendor, model, Android version, and your application behavior (the latter can partially [mostly?] be patched by the library you're using, Flutter Reactive BLE and Polidea RxAndroidBle in this case).

You may want to explicitly specify a reasonably short connection timeout (think of tens of seconds, I wouldn't recommend going below 20–30 seconds on Android) when calling `connect(⋯)` (please, check the documentation for the method). Then, in case of failure, you can retry.

**Comment by realrk69** [comment]
I think it's an application side error. Since my previous library was also having this problem (flutter blue) but I fixed it by listening to ScanResults while connecting to the device. Will have to see how to implement it here.

**Comment by werediver** [comment]
You should _not_ run discovery when connecting to peripherals (i.e. only _before_ that) from Android devices. Android BLE stack often cannot handle this well.

**Comment by realrk69** [comment]
I tested on 2 devices and it seems to connect to esp32 easily compared to nrf. Is there any way to change the scan mode to low latency or balanced?

**Comment by werediver** [comment]
You should check the API its documentation in the first place: [reactive_ble.dart#L233](https://github.com/PhilipsHue/flutter_reactive_ble/blob/f55da67d0c9ed977741730979d4122978a953066/lib/src/reactive_ble.dart#L233)

**Comment by realrk69** [comment]
Got it, I was not disconnecting the device before relaunching the app. Actually, the complication is that I'm using a single page for managing everything related to connections, so it takes some optimization. Thanks for your help
