### ISSUE TITLE
Provide in-app access to location

### ISSUE THREAD

**Issue by realrk69** [PhilipsHue/flutter_reactive_ble#161]
**Is your feature request related to a problem? (please describe)**
Why we cannot ask for permissions to access location (in-app) and have to do it app settings separately?

**Describe the solution you'd like**
It would be great to have this functionality inbuilt. Just showing the status would not be enough for some users to understand what to do. If it is at all possible through other methods, let me know.

**Comment by remonh87** [comment]
@realrk69 our library provides you with knowledge whether or not the location is approved. How to handle this in the UI should not be part of the library (some consumers would be happy with a simple popup and others would like a more elaborative screen). I would suggest something like:  https://pub.dev/packages/permission_handler which is tailored for your use case.
