### ISSUE TITLE
iOS debug and production build both fail when attempting to subscribe to characteristics

### ISSUE THREAD

**Issue by plyrek** [PhilipsHue/flutter_reactive_ble#169]
Sorry to double post this. Please merge into issue #137. I just wanted to elevate the issue because there does not seem to be any movement on it since last month.

**Original Post**
**Describe the bug**

**To Reproduce**
1. Connect to one / many devices using `connectTo()` / `connectToAdvertisingDevice()`
2. Read from / write to / subscribe to a protected / non-protected characteristic
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Expected behavior**

- [ ] I tried doing the same with a general BLE scanner application (e.g. [nRF Connect](https://duckduckgo.com/?q=nRF+connect)) and it exhibits the expected behavior as described above

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [e.g. 1.0.0]

**Peripheral device**
- Vendor, model: [e.g. Fitbit Versa, iPhone SE, or CUSTOM]
- Does it run a custom firmware / software: yes / no

**Additional context**

**My additions**
https://github.com/PhilipsHue/flutter_reactive_ble/issues/137#issuecomment-740205205

Thank you for your attention!

**Comment by werediver** [comment]
Hi, @plyrek. Thank you for reporting. Indeed, your issue matches #137 (you may want to subscribe to updates to that thread). I'll close this one as a duplicate.

I will try to get some time for this issue next week (Dec 14th onward).
