### ISSUE TITLE
Expose characteristic properties (read/write/notify/...)

### ISSUE THREAD

**Issue by werediver** [PhilipsHue/flutter_reactive_ble#181]
**Is your feature request related to a problem?**

This is a follow-up on #179.

**Describe the solution you'd like**

The library should expose BLE characteristic properties ([iOS doc](https://developer.apple.com/documentation/corebluetooth/cbcharacteristic/1519010-properties)).

**Describe alternatives you've considered**

Without exposing BLE characteristic properties, the only way to judge whether a particular property is set is to attempt performing the corresponding operation and judge by the outcome (which is also problematic, because of obscure exceptions thrown by the library).

**Comment by DevNico** [comment]
Can this issue get some attention please would like to see this feature as well.
