### ISSUE TITLE
Build failed with an exception when added to dependencies

### ISSUE THREAD

**Issue by JKornberg** [PhilipsHue/flutter_reactive_ble#202]
**Describe the bug**
Unable to build my project on an Android emulator when adding `flutter_reactive_ble: ^2.7.2` to the pubspec.yaml.

**To Reproduce**
1. Add flutter_reactive_ble: ^2.7.2
2. Run project on Android Emulator in debug mode on Visual Studio Code

The error I receive is:
>A problem occurred configuring project ':flutter_reactive_ble'.
> Failed to notify project evaluation listener.
   >com.android.build.gradle.internal.variant.BaseVariantData.getScope()Lcom/android/build/gradle/internal/scope/VariantScope;

**Expected behavior**
App should run properly

- [ ] I tried making a fresh project and adding it to pubspec.yaml and same thing happened

**Smartphone / tablet**
 - Device: Pixel 4 XL API 30 Emulator
 - OS: Android
 - Package version: ^2.7.2

**Additional context**
Am I not allowed to run this app on emulators? I'm sorry if this is documented somewhere but I could not find it.

**Comment by denkoul** [comment]
same problem here

**Comment by remonh87** [comment]
@JKornberg  can you send me the output of `flutter doctor`  and also provide me the version of Android studio + gradle wrapper and the android-tools version you are using?   The app builds properly on my machine on flutter stable and beta with stable Android studio.

**Comment by denkoul** [comment]
With the following configuration, the plugin is working:
`com.android.tools.build:gradle:4.0.1` in android/build.gradle
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip` in gradle wrapper properties

When I update gradle to 4.1.0 and distr url set to gradle-6.5 (required to run ndk.debugSymbolLevel) , the plug in crashes with the following error:
`A problem occurred configuring project ':flutter_reactive_ble'.
> Failed to notify project evaluation listener.
   > com.android.build.gradle.internal.variant.BaseVariantData.getScope()Lcom/android/build/gradle/internal/scope/VariantScope;`

**Comment by remonh87** [comment]
Hmm this looks likes a bug will investigate this in the coming days. Probably we need to update some android native dependencies on our site.

**Comment by remonh87** [comment]
Issue is resolved in version: `2.7.3`
