### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by lukepighetti** [PhilipsHue/flutter_reactive_ble#220]
Wanted to start an issue for tracking null safety migration for this package.

Is there any information to share about the future of null safety within `flutter_reactive_ble`?

**Comment by remonh87** [comment]
There is already a branch called `null-safety` . The library is fully migrated but I am not super happy about the api yet (too many nullable types). Hope to find time coming week to improve things there and ship the first version.

Let’s continue further discussion in #130 .
