### ISSUE TITLE
Is it possible to synchronize several subscribeToCharacteristic? 

### ISSUE THREAD

**Issue by LorenzoMonti** [PhilipsHue/flutter_reactive_ble#224]
In my project, I have different sensors, one for each characteristic. I would like to sync all my characteristics at time t. Has something already been implemented from this point of view? I haven't found anything in the documentation. 

Thank you in advance.

**Comment by werediver** [comment]
It's not clear what do you mean by "different sensors, one for each characteristic". Do you mean you have a _peripheral_ with multiple sensors or multiple peripherals, each sending updates? Either way, the updates are not coming in simultaneously (that is not possible via a single RF link in principle). In case of multiple peripherals you shouldn't even assume that you'll always get the same number of updates from every sensor over a period of time (clock drift, RF interference, power outage, etc.).

That is to say that talking about "syncing" updates is not very productive. I'd recommend to come up with a different problem formulation. Something like "collecting most recent updates, not older than a certain age". It may be more or less sophisticated, depending on your exact requirements.

Any way, this sounds like an entirely application level problem that should be solved outside of the library.
