### ISSUE TITLE
Extend example App with read/write and subscribe operations

### ISSUE THREAD

**Issue by remonh87** [PhilipsHue/flutter_reactive_ble#226]
**Describe the solution you'd like**
Extend example App with read/write and subscribe operations so it becomes easier to triage issues. It will be only implemented on the null-safety branch since in the future this becomes the main branch.

**Comment by werediver** [comment]
Would be nice if the added functionality (or at least a part of it) can be tested with some widespread hardware, like a second smartphone. They may expose some standard BLE services like time service.
