### ISSUE TITLE
How do I setup project for fork modifications?

### ISSUE THREAD

**Issue by LEMUSADR000** [PhilipsHue/flutter_reactive_ble#244]
I was wanting to create a fork with a raw scan record object available for Android users. The devices I'm using don't follow the proper bluetooth specifications for Android. This makes it so that I'm always missing 2 bytes of data in the manufacturer data so I'm just going to add the raw scan record bytes object to the DiscoveredDevice class. 

I'm struggling to get the project set up to do this. It seems there is a ProtobufModel object but it doesn't exist, so I'm guessing there is some command I have to run in order to generate that? If so, what is it?

**Comment by remonh87** [comment]
@LEMUSADR000  If you need to generate protobuf for dart or swift please follow these instructions: https://github.com/PhilipsHue/flutter_reactive_ble/tree/master/protos .

For android I use the protobuf gradle plugin and this is generated from scratch. Maybe cleaning project and then rebuilding will do the trick

**Comment by LEMUSADR000** [comment]
Thank you very much!
