### ISSUE TITLE
it not working for samsung android version 10 

### ISSUE THREAD

**Issue by jimykhan** [PhilipsHue/flutter_reactive_ble#249]
BLE support array set: 111111 a kind of log show

**Comment by werediver** [comment]
Unfortunately the information provided is not enough to take any action or to provide you with any advice.

Please, consider using the suggested issue template and put some effort in explaining in details the issue you are experiencing and what exactly you expect instead.

**Comment by remonh87** [comment]
Due to inactivity I will close this issue
