### ISSUE TITLE
Document needs prompt Android min SDK Level change 21 in the default flutter project

### ISSUE THREAD

**Issue by yihuishou** [PhilipsHue/flutter_reactive_ble#256]
**Describe the bug**

![2021-04-08_9-54-06](https://user-images.githubusercontent.com/26241263/113971242-fa67e400-986a-11eb-9a6e-83c171f9cea3.png)

**Comment by remonh87** [comment]
we support android 5 and higher and the Android sdk in your app does not support BLE (it is introduced in sdk 18).  You need to increase the sdk version in your android app to  21 (use the `mindsdk` property in build.gradle) in order to use this library.
