### ISSUE TITLE
Receive read characteristic notifies while iOS is minimized.

### ISSUE THREAD

**Issue by safield** [PhilipsHue/flutter_reactive_ble#259]
My app receives read characteristic notifies from a bluetooth device at regular 2 second intervals.

When the app is minimized on Android, those notifies continue to propagate to my app. When on iOS these notifies immediately cease once the app is minimized.

Is there a way to receive notifies in the background on iOS, or is this simply a limitation of the iOS platform?

**Comment by remonh87** [comment]
@werediver  can you answer this question? think it should work normally.

**Comment by werediver** [comment]
@safield Please refer to [Core Bluetooth Background Execution Modes](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html#//apple_ref/doc/uid/TP40013257-CH7-SW7). You may need to declare `bluetooth-central` background execution mode, if you want to process notifications when your app is minimized.

I assume this resolves the question.

**Comment by roberoad** [comment]
@safield did this work for you? I need to get continued updates from my BLE device when app is not in foreground and I'm struggling to find anyone successfully doing this with Flutter.

**Comment by jawadabbasi923** [comment]
@safield have you solved it ?
