### ISSUE TITLE
Support Android 12

### ISSUE THREAD

**Issue by remonh87** [PhilipsHue/flutter_reactive_ble#273]
**Is your feature request related to a problem? (please describe)**
I tested the library on Android 12 dev preview 3 and experience some issue reading characteristics. I open this ticket to make sure we are able to support Android 12 before it is launched to stable
**Describe the solution you'd like**
Support Android 12

**Additional context**
Dependency on Polidea library for fixing Android12: [link](https://github.com/Polidea/RxAndroidBle/issues/749)
- new ble permissions: https://developer.android.com/about/versions/12/features/bluetooth-permissions

**Comment by Balls107** [comment]
un

**Comment by PieterAelse** [comment]
@remonh87 I think the correct link to an issue on the Polidea library should be this one? https://github.com/Polidea/RxAndroidBle/issues/752
