### ISSUE TITLE
scanForDevices() twice causes crash on iOS

### ISSUE THREAD

**Issue by abegehr** [PhilipsHue/flutter_reactive_ble#283]
**Describe the bug**
I'm calling `scanForDevices()` twice and this causes a crash. See attached screenshot.

**To Reproduce**
1. Call `scanForDevices()` twice.

**Expected behavior**
It does not matter how often `scanForDevices()` is called and it does not cause a crash.

**Smartphone / tablet**
 - Device: iPhone 12 Pro
 - OS: iOS 14.6
 - Package version: 3.1.1

**Peripheral device**
not applicable

**Additional details**

Error:
```
flutter_reactive_ble/PluginController.swift:153: Assertion failed
* thread #1, queue = 'com.apple.main-thread', stop reason = Assertion failed
    frame #0: 0x00000001a615beac libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`_swift_runtime_on_report:
->  0x1a615beac <+0>: ret
libswiftCore.dylib`_swift_reportToDebugger:
    0x1a615beb0 <+0>: b      0x1a615beac               ; _swift_runtime_on_report
libswiftCore.dylib`_swift_shouldReportFatalErrorsToDebugger:
    0x1a615beb4 <+0>: adrp   x8, 337038
    0x1a615beb8 <+4>: ldrb   w0, [x8, #0xef9]
Target 0: (Runner) stopped.
Lost connection to device.
Exited (sigterm)
```

Screenshot:
![Screenshot 2021-05-28 at 21 40 59](https://user-images.githubusercontent.com/23075874/120034958-1b90b980-bffe-11eb-8018-f185859a87ce.png)

**Comment by Taym95** [comment]
This assert is being triggered 
https://github.com/PhilipsHue/flutter_reactive_ble/blob/master/ios/Classes/Plugin/PluginController.swift#L153

You need to call `stopScanning` before calling the second `scanForDevices`

**Comment by abegehr** [comment]
Thanks for the info!

**Comment by abegehr** [comment]
Actually, @Taym95, I'm not finding stopScanning() on the FlutterReactiveBle service: https://pub.dev/documentation/flutter_reactive_ble/latest/flutter_reactive_ble/FlutterReactiveBle-class.html.
I'm on the lastest version 3.1.1+1.

**Comment by werediver** [comment]
@abegehr To terminate a scan you need close the stream returned when the scan is started. Same as with a connection: to terminate it you just close the connection status stream returned when the connection was initiated.

**Comment by werediver** [comment]
I suppose, the original issue is resolved through explanation. The library API design reflects the underlying BLE API.
