### ISSUE TITLE
Maintain connection with device after application termination

### ISSUE THREAD

**Issue by konopka90** [PhilipsHue/flutter_reactive_ble#294]
Is it somehow possible to maintain connection with BLE device after killing flutter application? 
I was trying to dive into the code but I have no idea if any function like "disconnect devices" is called during disposal.

**Comment by remonh87** [comment]
We always disconnect when the connectionstream is getting disposed, so killing the app results in disconnecting with the peripheral.  However the ble stack on the phone uses some caching so the next connect is relatively quick. In case you would like to use the ble connection in a background service I would suggest to look into: [background flutter](https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124).
