### ISSUE TITLE
Document RSSI range

### ISSUE THREAD

**Issue by petoknm** [PhilipsHue/flutter_reactive_ble#317]
What is the range of `rssi` values I should be expecting? I can't find this information in the documentation.
Is the range same or different on different platforms?
Is it linear for showing something like a bar strength indicator?

Thanks :)

**Comment by petoknm** [comment]
[maybe this?](https://developer.android.com/reference/android/net/wifi/WifiManager#calculateSignalLevel(int))

**Comment by remonh87** [comment]
RSSI is very volatile and complex and really depends on the strength of the radio from the phone and peripheral + interference (other BLE devices, WiFI etc.) . I think what google states is not a bat range to start with but doesn't mean you can get below or above it.

**Comment by remonh87** [comment]
And there is a difference between platforms. In general we found out that iOS devices tend to have more beneficial RSSI values compared to Android devices for our lights.
