### ISSUE TITLE
Characteristics update stream through data fail

### ISSUE THREAD

**Issue by zikambrani** [PhilipsHue/flutter_reactive_ble#330]
<img width="1191" alt="Screen Shot 2021-08-07 at 4 06 26 AM" src="https://user-images.githubusercontent.com/86159682/128583215-e5de2e34-b978-463b-8529-a27081c2a046.png">

due to uuid not mached

**Comment by remonh87** [comment]
Can you help us by filling in the issue template? At the moment we miss some important information:

- Operating system
- Device 
- version of the library
- Stacktrace
