### ISSUE TITLE
Upgrade flutter constraint to >=2.0.0 & remove deprecated embedding functions

### ISSUE THREAD

**Issue by juliansteenbakker** [PhilipsHue/flutter_reactive_ble#333]
This plugin still has functions for the old embedding v1. However, since this package is upgraded to null-safety and null-safety is only supported by flutter 2.0.0 and greater, we can safely remove the old implementation and bump the flutter constraint to 2.0.0 and greater. This is also used in official packages like the [camera](https://github.com/flutter/plugins/blob/acc3202466a8b4c0b1bcb91fc1ce520c7b021e44/packages/camera/camera/pubspec.yaml#L11) package.
```dart
        // this enables support for apps that are using the legacy implementation of the app
        @JvmStatic
        fun registerWith(registrar: Registrar) {
            initalizePlugin(registrar.messenger(), registrar.activeContext())
        }
```

```yaml
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0" # old: ">=1.10.0"
```

**Comment by werediver** [comment]
`">=2.0.0"` looks overly optimistic. I would stick to `^2.0.0` (or `">=2.0.0 <3.0.0"`).
