### ISSUE TITLE
How to Disconnect Device?

### ISSUE THREAD

**Issue by yuriboeira11tx** [PhilipsHue/flutter_reactive_ble#336]

**Comment by remonh87** [comment]
you disconnect a device buy cancelling the stream subscription.  See also our example app: https://github.com/PhilipsHue/flutter_reactive_ble/blob/ea29bd23152c4257294bb9e468950247cf98a63f/example/lib/src/ble/ble_device_connector.dart#L37

**Comment by yuriboeira11tx** [comment]
Thanks for your help, this lib is fantastically! <3
