### ISSUE TITLE
package com.signify.hue.flutterreactiveble does not exist (Android)

### ISSUE THREAD

**Issue by rohitranjan1991** [PhilipsHue/flutter_reactive_ble#344]
**Describe the bug**
I am getting the following issue while building my code with this plugin added in pubspec.yaml for Android.

Error: 

`GeneratedPluginRegistrant.java:35: error: package com.signify.hue.flutterreactiveble does not exist
    flutterEngine.getPlugins().add(new com.signify.hue.flutterreactiveble.ReactiveBlePlugin());`

**To Reproduce**
1. Add 4.0.0 version of this library
2. Try to run the code on a device
3. The build fails with the above exception

**Expected behavior**
The build should work

**Smartphone / tablet**
 - Device: Android
 - OS: Android 10
 - Package version: 4.0.0

@remonh87

**Comment by remonh87** [comment]
Did you follow the instructions provided:  https://github.com/PhilipsHue/flutter_reactive_ble#setup ?

**Comment by rohitranjan1991** [comment]
@remonh87 , Yes I did. I have set all the required permissions. Also, I have set the proguard rule also. Please let me know what else could I be doing wrong. Thanks.

**Comment by remonh87** [comment]
I tried the same and for me it works without issues. You probably also did a flutter clean and rebuild the app?
