### ISSUE TITLE
BLE undeliverable exception - need more documentation on how to implement it

### ISSUE THREAD

**Issue by chris-otani** [PhilipsHue/flutter_reactive_ble#345]
I'm struggling to add the workaround for the BLE undeliverable exception to my flutter project. I have no Java/Kotlin experience and searched but can't figure out how to properly add it.

I've added the code to my MainActivity.kt but am getting errors. Could you provide more detail on where to add this code?

> error: expecting member decleration

![2021-08-19_16-54-21](https://user-images.githubusercontent.com/77981417/130142573-f3aa8048-1b7d-475c-baa3-d80d241ed0af.png)

When I try to run it I get:

> Unresolved reference: throwable
> FAILURE: Build failed with an exception.

CODE:

```
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
    RxJavaPlugins.setErrorHandler { throwable ->
        if (throwable is UndeliverableException && throwable.cause is BleException) {
            return@setErrorHandler // ignore BleExceptions since we do not have subscriber
        }
        else {
            throw throwable
        }
    }
}
```

Any help would be greatly appreciated.

**Comment by remonh87** [comment]
Do not forget to add

`implementation "com.polidea.rxandroidble2:rxandroidble:1.11.1"` to your gradle dependencies and fix the imports

**Comment by chris-otani** [comment]
@remonh87 , thanks for the quick response.

I added that to my gradle dependicies. I also added rxkotlin since it couldn't find that package.

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.polidea.rxandroidble2:rxandroidble:1.11.1"
    implementation 'io.reactivex.rxjava2:rxkotlin:2.4.0'
}
```

When fixing the imports it looks like It's not properly importing the "RxJavaPlugins".  the import is greyed out like its not being used

MainActivity.kt
```
import io.flutter.embedding.android.FlutterActivity

import com.polidea.rxandroidble2.exceptions.BleException
import io.reactivex.exceptions.UndeliverableException
import io.reactivex.plugins.RxJavaPlugins

class MainActivity: FlutterActivity() {
    RxJavaPlugins.setErrorHandler { throwable ->
        if (throwable is UndeliverableException && throwable.cause is BleException) {
            return@setErrorHandler // ignore BleExceptions since we do not have subscriber
        }
        else {
            throw throwable
        }
    }
}
```

Here are the static errors:

![2021-08-20_09-36-23](https://user-images.githubusercontent.com/77981417/130241666-13f81e4f-be6c-423f-863b-752ed90f458c.png)

**Comment by keval-devani** [comment]
Just change your code like this in your MainActivity
```
import android.os.Bundle
import com.polidea.rxandroidble2.exceptions.BleException
import io.flutter.embedding.android.FlutterActivity
import io.reactivex.exceptions.UndeliverableException
import io.reactivex.plugins.RxJavaPlugins

class MainActivity : FlutterActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        RxJavaPlugins.setErrorHandler { throwable ->
            if (throwable is UndeliverableException && throwable.cause is BleException) {
                return@setErrorHandler // ignore BleExceptions since we do not have subscriber
            } else {
                throw throwable
            }
        }
    }
}

```
