### ISSUE TITLE
Generalization beyond Strings to include ByteData

### ISSUE THREAD

**Issue by farr64** [PhilipsHue/flutter_reactive_ble#348]
**Is your feature request related to a problem? (please describe)**

Not a problem but a question of generalization beyond Strings to include `ByteData` as a superset.

Sending Strings back and forth via BLE works great but this method is inefficient (in terms of space) with numeric data such as `int` and `float`.

`ByteData` arrays can pack much more punch in less space. 
https://api.flutter.dev/flutter/dart-typed_data/ByteData-class.html

Getting BLE packets that contain **only String values** works perfectly with
`Stream<List<int>> subScribeToCharacteristic()`

It would be convenient to also be able to get **NON-String** BLE packets that contain `ByteData` (with integer  values that may be equal to zero in the middle of a `ByteData` array).

Unfortunately, `Stream<List<int>> subScribeToCharacteristic()` seems to interpret any integers that are zero in the middle of a `ByteData` array as the end of the received "String" (which is NOT really a string but a bunch of binary bytes) and the information gets truncated.

**Describe the solution you'd like**

**Perhaps it's possible to get ByteData now** (including integers that are zero in the middle of the `ByteData` array, without truncating the "String"), but I haven't been able to figure out how to do it. 

**If it is possible,** could you please add some comments in the documentation regarding how to deal with `ByteData` arrays that have integers that are zero in the middle (preventing them from becoming truncated at the first zero)?

**If it's not possible now, then please consider this as a feature request to deal with ByteData in addition to Strings.**

Thank you.

**Comment by remonh87** [comment]
@farr64  can't you use `byteData.buffer` and then convert this properly? I think byte buffer should enable you to avoid this problem: https://api.flutter.dev/flutter/dart-typed_data/ByteBuffer-class.html .

**Comment by farr64** [comment]
@remonh87 

That would be great. The question is how to make that type compatible with your
`Stream<List<int>> subScribeToCharacteristic()`
(which specifies type `List<int>`).

If you could please provide some guidance for the specific way to make `byteData.buffer` compatible with your `Stream<List<int>> subScribeToCharacteristic()`, I would be grateful.

**Comment by Taym95** [comment]
I did really understand your question but I think you want to create `byteData.buffer` from `List<int>`?

```
List<int> dataFromStream;
final bytes = Uint8List.fromList(dataFromStream).buffer;
final byteData = ByteData.view(bytes);
```
and you can do whatever you want with `byteData`

**Comment by farr64** [comment]
@Taym95 Perfect. This accomplishes precisely what I needed.

I write embedded apps in C and I'm now learning to access (and control) embedded systems with Flutter apps using your `flutter_reactive_ble` library.

As I learn Dart, I'm learning to translate concepts that are trivial in C (such as structs and unions, which are useful in dealing with raw bits and bytes) into the appropriate Dart idioms.

I hope this knowledge will also help other users of your `flutter_reactive_ble` library who are dealing with close-to-the-metal embedded systems.

Thank you very much for having shared your fluency with Dart idioms.
