### ISSUE TITLE
Improve architecture example app

### ISSUE THREAD

**Issue by remonh87** [PhilipsHue/flutter_reactive_ble#35]
**Is your feature request related to a problem? (please describe)**
The architecture does not reflect a super nice way how to user our library in the app

**Describe the solution you'd like**
Extract BLE related code into a seperate component (e.g. BLOC)

**Comment by werediver** [comment]
Thanks @remonh87 for completing that great redesign in #38 🎉

If we have more ideas on this topic, we can track them with new tickets.
