### ISSUE TITLE
I could not get the device that was already connected, which caused me to be unable to disconnect the specified device  

### ISSUE THREAD

**Issue by jahnli** [PhilipsHue/flutter_reactive_ble#353]
**Is your feature request related to a problem? (please describe)**

I could not get the device that was already connected, which caused me to be unable to disconnect the specified device  

**Describe the solution you'd like**

Similar to flutter blue. ConnectedDevices

**Describe alternatives you've considered**

**Additional context**

**Comment by jahnli** [comment]
When I have successfully connected multiple devices, I should dispose the connected devices and close them.

**Comment by jahnli** [comment]
When I have successfully connected multiple devices, how do I dispose the connected devices and close them?

**Comment by Taym95** [comment]
Can't you implement this logic in your app? why you want it inside the library?

**Comment by jahnli** [comment]
I did not find in the document how to obtain the connected device

**Comment by jahnli** [comment]
I would like to get multiple connected devices and close them each time I dispose them, but I can't do it now

**Comment by remonh87** [comment]
when you listen to a stream you will have a streamsubscription object. What you can do is add that collection to a Map and then cancel the specific subscription when you do not need it anymore.

**Comment by jahnli** [comment]
Does that mean I need to add the map object successfully obtained from the connection to a list and then loop to call cancel()?

**Comment by remonh87** [comment]
For example and if you use the deviceID as key then it is quite simple to disconnect specific devices

**Comment by jahnli** [comment]
At present, there is a scenario: when I hot reboot on this page, the device cannot be disconnected and bluetooth remains connected

**Comment by jahnli** [comment]
Is it possible to provide an API like Flutter_blue's connectedDevices
