### ISSUE TITLE
ConnectToDevice Sometimes fast, sometimes slow

### ISSUE THREAD

**Issue by jahnli** [PhilipsHue/flutter_reactive_ble#354]
**Describe the bug**

**To Reproduce**
1. Connect to one / many devices using `connectTo()` / `connectToAdvertisingDevice()`
2. Read from / write to / subscribe to a protected / non-protected characteristic
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

1.connectToDevice

**Expected behavior**

When I try connectToDevice, sometimes the connection speed is fast, sometimes the connection speed is slow, I don't know how to optimize  

- [ ] I tried doing the same with a general BLE scanner application (e.g. [nRF Connect](https://duckduckgo.com/?q=nRF+connect)) and it exhibits the expected behavior as described above

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [e.g. 1.0.0]

**Peripheral device**
- Vendor, model: [e.g. Fitbit Versa, iPhone SE, or CUSTOM]
- Does it run a custom firmware / software: yes / no

**Additional context**

**Comment by jahnli** [comment]
android ，xiaomi

When I try to connect multiple times, sometimes it takes 10 seconds, sometimes it takes 2-3 to connect successfully

**Comment by remonh87** [comment]
this sounds like you are connecting using the `autoConnect` flag what you can try out is specifying a connection timeout (like for example between  5-10 seconds) . In that case we do not use auto connect and I expect things will run smoother.

**Comment by jahnli** [comment]
I don't set the automatic connection. What's the reason why the automatic connection is fast or slow by default?

**Comment by remonh87** [comment]
When doing auto connect you tell Android connect whenever you see this device. This call never times out and we found out during our experiments that the time of connecting varies a lot between session.

**Comment by Abhishek01039** [comment]
Hello @jahnli 
I am not able to connect with the device. what could be the problem here (I am using the example which is given here)?

```
D/BluetoothGatt( 5907): connect() - device: 7B:27:52:62:64:D7, auto: true
D/BluetoothGatt( 5907): registerApp()
D/BluetoothGatt( 5907): registerApp() - UUID=ab075d8c-8d82-4c3e-a59a-052bf7cfb02e
I/flutter ( 5907): ConnectionState for device 7B:27:52:62:64:D7 : DeviceConnectionState.connecting
D/BluetoothGatt( 5907): onClientRegistered() - status=0 clientIf=8
```

**Comment by remonh87** [comment]
@jahnli  @Abhishek01039 . Bluetooth (especially on Android) is not a reliable protocol when it comes to connecting.  There is nothing from library perspective what we can do against it.  I would play a bit around with providing a connectionTimeOut or no (this will either use android auto connect or not). 

https://github.com/PhilipsHue/flutter_reactive_ble/blob/06f727777985403abc498cb5b246dbf137911119/packages/flutter_reactive_ble/lib/src/reactive_ble.dart#L284

**Comment by jahnli** [comment]
thanks
