### ISSUE TITLE
Name is not coming of scanned devices

### ISSUE THREAD

**Issue by Abhishek01039** [PhilipsHue/flutter_reactive_ble#357]
**Describe the bug**
I am not able to get the name of the device which is scanned by this plugin.

**To Reproduce**
1. Scan for devices using `scanForDevices()`
2. get the stream of `DiscoveredDevice`
3. I am not able to get the name of the device (Only MAC address is coming)

**Expected behavior**

- [ ] I tried doing the same with a general BLE scanner application (e.g. [nRF Connect](https://duckduckgo.com/?q=nRF+connect)) and it exhibits the expected behavior as described above

**Smartphone / tablet**
 - Asus zenfone pro M1
 - OS: [Android 9]
 - Package version: [4.0.0]

**Comment by Abhishek01039** [comment]
@remonh87 
can you please look into it?
thanks

**Comment by Taym95** [comment]
Can you please test it on nRF Connect and see if you are getting the name?

**Comment by Abhishek01039** [comment]
I am getting the name of nordic devices

Thank you!
