### ISSUE TITLE
Android 12 permission system

### ISSUE THREAD

**Issue by juliansteenbakker** [PhilipsHue/flutter_reactive_ble#370]
**Describe the bug**
With Android 12 new permissions are introduced which are required to utilize bluetooth functionality.

**To Reproduce**
Right now, projects which target API 31 are failing because the permission android.permission.BLUETOOTH_SCAN is not set.

**Expected behavior**
Apply the new permissions as described here: https://developer.android.com/about/versions/12/features/bluetooth-permissions

The page also describes how to use `android:maxSdkVersion="30"` on the existing permissions to keep backwards compatibility with older SDK.

**Smartphone / tablet**
All android 12 devices.

**Comment by PieterAelse** [comment]
Hi Julian, we already have issue https://github.com/PhilipsHue/flutter_reactive_ble/issues/273 and it's linked to this issue in Polidea library: https://github.com/Polidea/RxAndroidBle/issues/752

**Comment by juliansteenbakker** [comment]
My bad, i didn't saw it right away. Maybe it's a good idea to pin the issue since it's blocking Android 12 apps and i'm sure more people will run into this.

**Comment by PieterAelse** [comment]
@juliansteenbakker Good suggestion! I've pinned the issue 👍
