### ISSUE TITLE
Get list of already connected peripherals before scanning

### ISSUE THREAD

**Issue by vincent290587** [PhilipsHue/flutter_reactive_ble#379]
I was wondering if there is any way to check if the device we want to connect to is already connected to the phone.
I my case, the device pairs itself to the phone, and connects automatically.

I have not found a way yet to check if the device is already connected before scanning.

Have I overlooked something ?

**Comment by remonh87** [comment]
it is actually sth I would like to add in the future releases . it is also a duplicate of: #322 (issue is different but same solution).

**Comment by b055man** [comment]
@remonh87 Is there any issue that tracks this then? 322 is closed now, without any solution.
