### ISSUE TITLE
iOS scan returning devices that are not advertising. 

### ISSUE THREAD

**Issue by yuriboeira11tx** [PhilipsHue/flutter_reactive_ble#390]
I found that while the service search works, in a way that filters only convenient devices. On iOS, after this device is found by the API, even if it stops propagating and you restart the scan the device will show up. On Android this does not happen. What is to understand is that the iOS BLE system keeps certain device IDs and even if they are not advertising they will be recognized to connect. Any suggestions to fix this? Clear any cache possible?

**Comment by remonh87** [comment]
Deleting the cache can only be done manual as far as I know but maybe you can check  create a workaround: consider a device to be advertising when you got at least 2 updates of the device. Of course this comes at a cost of performance but I do not see any other way to prevent this at the moment.
