### ISSUE TITLE
v4.0.1 contains nullability errors when integrated with Xcode 13. 

### ISSUE THREAD

**Issue by vmammanalupo** [PhilipsHue/flutter_reactive_ble#394]
I know there were other reports of this using a version of Xcode < 13, but I have read those threads carefully and am at a bit of a loss to why the plugin contains these issues. Part of the mystery is that my other team members do not experience any issues. We have aligned on tooling:

Xcode 13.0
Flutter 2.5.1 SDK
Dart 2.14.2
Cocoapods 1.11.2
flutter_reactive_ble 4.0.1

I have 
- completely nuked all caches
- cleared derived data
- cleaned the project 
- restarted the computer
- removed build folders 
- did a complete reinstall of dependencies for the flutter project. 

Android doesn't have any issues but iOS contains the prior reported code issues. Were you guys able to find out any other information from the closed threads? This seems like another component is problematic, as the proposed PR seems to be a fixed designed for users of older versions ( < 13)  of Xcode. 

**To Reproduce**
1. Integrate v4.0.1 of `flutter_reactive_ble`
2. Attempt to build for iOS
3. Observe build failures 
<img width="1204" alt="Screen Shot 2021-09-30 at 5 26 58 PM" src="https://user-images.githubusercontent.com/11654738/135548445-45a60147-303f-446b-842d-8b4e089b593c.png">

**Expected behavior**
No errors with the module

**Smartphone / tablet**
 - Device: iPhone XS Max Simulator
 - OS: iOS 15
 - Package version: 4.0.1

**Peripheral device**
- Vendor, model: Custom
- Does it run a custom firmware / software: yes

**Additional context**
This is more of a shot in the dark. Again, I do not doubt that this works for some people, but I was curious to be able to understand why it is not working as intended for me. Was just hoping for suggested recommendations on what else I can do here. Related threads [Issue 372](https://github.com/PhilipsHue/flutter_reactive_ble/issues/372), [Issue 373](https://github.com/PhilipsHue/flutter_reactive_ble/issues/373), [Issue 386](https://github.com/PhilipsHue/flutter_reactive_ble/issues/386) all seem to have issues with older versions of Xcode, but I am using Xcode 13.

**Comment by remonh87** [comment]
@vmammanalupo  it looks like you have an old version of the `reactive_ble_mobile` library. Can you make sure you have set that version to `4.0.1` in your pub spec.lock ?

**Comment by vmammanalupo** [comment]
@remonh87 Thanks so much for the reply. 

I did confirm that I do have `4.0.1` integrated in my `pubspec.yaml` and `pubspec.lock` .  I still deleted the pubspec.lock, re-performed a `flutter pub get` and a `pod install`. Same issue occurs when trying to build. 

<img width="799" alt="Screen Shot 2021-09-30 at 10 33 51 PM" src="https://user-images.githubusercontent.com/11654738/135571039-22b3cdb3-d5eb-402f-9dd7-01ff11dcc3d4.png">

Do you know if there is any versioning with the `reactive_ble_mobile` library? looks to be set to `0.0.1`.

**Comment by vmammanalupo** [comment]
<img width="570" alt="Screen Shot 2021-09-30 at 10 43 23 PM" src="https://user-images.githubusercontent.com/11654738/135571385-c563c11f-3729-4e69-842e-1fb304973a59.png">

Here is an image of the `pubspec.yaml` as well. It is set to `4.0.1`. We avoid any `^` usage so CI doesn't have the potential to update plugins.

**Comment by meamde** [comment]
i have a same error when build with xcode 12.4 and flutter 2.5...

**Comment by jalpedersen** [comment]
Check that your iOS deployment target is >= 11

**Comment by vmammanalupo** [comment]
> _i have a same error when build with xcode 12.4 and flutter 2.5..._
> 
> oh, my problem solved with dependcy_overrides 4.0.0.

Yeah the dependency override is a solution for users with versions of Xcode < 13. I am experiencing problems on Xcode 13.0 which isn't covered.

**Comment by vmammanalupo** [comment]
@jalpedersen 

> Check that your iOS deployment target is >= 11

I have the ios version set to `13.0` for the main target and all pods

<img width="756" alt="Screen Shot 2021-10-01 at 8 31 10 AM" src="https://user-images.githubusercontent.com/11654738/135648497-21c8c21b-4d56-455d-b70b-990dc2afded4.png">

<img width="850" alt="Screen Shot 2021-10-01 at 8 30 47 AM" src="https://user-images.githubusercontent.com/11654738/135648517-f4f08915-3ebc-4e69-a9ff-a74024440b79.png">

**Comment by vmammanalupo** [comment]
I have tried playing around with the deployment target values, but I always make sure to `pod install` after to make sure it actually integrates the changes

**Comment by vmammanalupo** [comment]
<img width="966" alt="Screen Shot 2021-10-01 at 9 33 37 AM 1" src="https://user-images.githubusercontent.com/11654738/135656547-11ddca45-6961-49be-b6c9-e98ee3e9e258.png">

From the podfile.lock I confirmed with my team members that it _looks to be pulling in the same library commit_ as what is working for them

**Comment by vmammanalupo** [comment]
Cocoapods seemed to be deceiving me on what it was integrating... I removed the library from the `pubspec.yaml` completely and ran a  `flutter pub get` and then a `pod install`.

Attempted to build the project knowing it would fail without the `flutter_reactive_ble` plugin.

Then performed `pod cache clean --all` and completely deleted the `podfile.lock`, `Pods` directory and the `build` directory in ios.

Did a `flutter clean` and readded the `flutter_reactive_ble 4.0.1` to the pubspec.yaml and `reintegrated` everything again.

Thanks for the help guys
