### ISSUE TITLE
[Question] How to disconnect ble device programmatically? 

### ISSUE THREAD

**Issue by JAICHANGPARK** [PhilipsHue/flutter_reactive_ble#395]
Hello 

I'd like to disconnect my device using code 
but cleargattcache is not working for me 

any have method to disconnect process?

**Comment by remonh87** [comment]
you can disconnect the device by cancelling the stream when connecting to the device. See also our example app.

**Comment by JAICHANGPARK** [comment]
@remonh87  Than you for supporting
