### ISSUE TITLE
Location Permission missing (code 3)

### ISSUE THREAD

**Issue by meridorkobi** [PhilipsHue/flutter_reactive_ble#397]
I'm trying to scan in the background and I have this error
I also tried with requireLocationServicesEnabled:true

**Code**
```
      flutterReactiveBle.scanForDevices(withServices: [],requireLocationServicesEnabled:false).listen((device)  {
          //code for handling results
          print("service - blue - " + device.name.toString());
          }, onError: (error) {
            print('service - blue - error!' + error.toString());
          });
```
**plugins**
lutter_reactive_ble - 4.0.1
flutter_background_service - 0.1.5

**full error**
 GenericFailure<ScanFailure>(code: ScanFailure.unknown, message: "Location Permission missing (code 3)")

**Comment by remonh87** [comment]
you need to enable location permissions. See https://github.com/PhilipsHue/flutter_reactive_ble#which-permissions-are-needed

**Comment by meridorkobi** [comment]
I did it
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />

**Comment by meridorkobi** [comment]
> you need to enable location permissions. See https://github.com/PhilipsHue/flutter_reactive_ble#which-permissions-are-needed

Can you reopen please

**Comment by remonh87** [comment]
but also you need to make sure your permission is granted.

**Comment by meridorkobi** [comment]
> but also you need to make sure your permission is granted.

Can I scan without the location.
I don't need the location

**Comment by EdoardoVignati** [comment]
I fixed requesting the permission:
`await Permission.location.request();`
