### ISSUE TITLE
Broadcast as a beacon

### ISSUE THREAD

**Issue by faheem4797** [PhilipsHue/flutter_reactive_ble#398]
Does this package allows us to broadcast our device as a beacon? If yes then can you please point me towards the method/property. 
Or does this package just allows us to scan for devices and i have to use something else to first broadcast as a beacon?

**Comment by faheem4797** [comment]
So I did broadcast as a beacon using 'beacon_broadcast'. [https://pub.dev/packages/beacon_broadcast](url) 
![image](https://user-images.githubusercontent.com/75106797/135869918-75e0a3cc-99f4-4e1e-9203-07145380e0d4.png)


And I have checked the results in Beacon Simulator (an app on play store). Which is working fine and UUID is visible etc.
![image](https://user-images.githubusercontent.com/75106797/135870399-df3fac3a-e7b6-43b0-8da3-cf91bdde1c89.png)


The issue is that when I scan the same beacon through 'flutter_reactive_ble'. The result doesnt show any service data.
![image](https://user-images.githubusercontent.com/75106797/135870471-0d76d7fe-8ffe-4a9b-8a70-5cccc6b5b7b3.png)


I am also calling scanfordevices with the uuid but not getting the desired result. I want serviceData to be shown here.
![image](https://user-images.githubusercontent.com/75106797/135869787-5dfab703-0006-4358-8388-21ecdb871165.png)

Can you please tell me what i am doing wrong here? or point towards the solution. Will be much thankful.


Both the devices are Android 9 (API 28).

**Comment by remonh87** [comment]
can you check with a bluetooth explorer like nrf connect if the device has service data? The good thing is that the advertisement packet is there but for some reason the service data is not filled are you sure that the device has service data?

**Comment by matiasleyba** [comment]
@faheem4797 can you explain the solution ? I have a simliar issue... I cant detect the device

**Comment by faheem4797** [comment]
@matiasleyba i think i dropped the whole service data idea and just sent some data through manufacturerdata and used some logic to compare after scanning  (i was making a school project so not recommended for actual industry level solution).

 Also instead of "beacon_broadcast" package (https://pub.dev/packages/beacon_broadcast) used the flutter_ble_peripheral (https://pub.dev/packages/flutter_ble_peripheral) (not recommended if you are making ios app aswell)

**Comment by matiasleyba** [comment]
@faheem4797 thanks for response, I resolved the issue, it was bad code, i forgot to manage the beacon layout correctly
