### ISSUE TITLE
[Question] requestMtu take too many time

### ISSUE THREAD

**Issue by JAICHANGPARK** [PhilipsHue/flutter_reactive_ble#405]
**Describe the bug**
Hello
I set the first 200 bytes using the requestMtu method.
At first, the setup goes well with no problems. However, when requestMtu is made with 20 bytes again, it takes a very long time to process. I wonder why this is happening.

**To Reproduce**

```
final mtu = await flutterReactiveBle.requestMtu(deviceId: foundDeviceId, mtu: 200);
some process()
final mtu = await flutterReactiveBle.requestMtu(deviceId: foundDeviceId, mtu: 20); <- take too many time

```

**Expected behavior**

- If you use the requestMtu method with 20 bytes, there is no other write read operation.

**Smartphone / tablet**
 - OS: Android 8 
 - Package version: 4.0.1 

**Peripheral device**
- ESP32

**Comment by remonh87** [comment]
Can you provide me some additional information?
1. What kind of operation are you executing in between: e.g. `writeWithoutResponse`. 
2. Do you have some logcat out put from the time it happens?
3. How long does requesting the MTU take ?
