### ISSUE TITLE
Build against Android 30 SDK Fails

### ISSUE THREAD

**Issue by pgiacomo69** [PhilipsHue/flutter_reactive_ble#410]
Build against Android 30 SDK Fails

**To Reproduce**
1. Upgrade Package to 5.0.0 in project
2. Build Against SDK 30, with minimum sdk 24
3. Build fails with this message:
 
```
Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bundleGooglePlayReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable
   > Android resource linking failed
     ERROR:D:\Flutter\........\build\app\intermediates\bundle_manifest\googlePlayRelease\AndroidManifest.xml:35: AAPT: error: attribute android:usesPermissionFlags not found.
```

**Comment by Taym95** [comment]
`error: attribute android:usesPermissionFlags not found`, you should not add API 31+ permissions to app on API30, example: 
`<uses-permission android:name="android.permission.BLUETOOTH_SCAN"android:usesPermissionFlags="neverForLocation" />` works only on API >= 31

**Comment by Taym95** [comment]
I managed to make it work by adding `tools:node="remove"` to 
`
 <uses-permission
            android:name="android.permission.BLUETOOTH_SCAN"
            android:usesPermissionFlags="neverForLocation" tools:node="remove" />
`
don't forgot to add `xmlns:tools="http://schemas.android.com/tools"` in the top.

@remonh87  If this is okay I can add it as doc in readme!

**Comment by Taym95** [comment]
> > I managed to make it work by adding `tools:node="remove"` to:
> > ```
> >  <uses-permission
> >             android:name="android.permission.BLUETOOTH_SCAN"
> >             android:usesPermissionFlags="neverForLocation" tools:node="remove" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > don't forgot to add `xmlns:tools="http://schemas.android.com/tools"` in the top of your manifest.
> > @remonh87 If this is okay I can add it as doc in readme!
> 
> But this should be used only with sdk<31? I’m curious to understand why this attribute is automagically set in sdk 30, and by who?

Yes should be used only with sdk<31

**Comment by safield** [comment]
I have this same problem. What is the correct course of action? Is there a fix incoming?

**Comment by Thidiyas3d** [comment]
> > > I managed to make it work by adding `tools:node="remove"` to:
> > > ```
> > >  <uses-permission
> > >             android:name="android.permission.BLUETOOTH_SCAN"
> > >             android:usesPermissionFlags="neverForLocation" tools:node="remove" />
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > don't forgot to add `xmlns:tools="http://schemas.android.com/tools"` in the top of your manifest.
> > > @remonh87 If this is okay I can add it as doc in readme!
> > 
> > 
> > But this should be used only with sdk<31? I’m curious to understand why this attribute is automagically set in sdk 30, and by who?
> 
> Yes should be used only with sdk<31

Thanks @Taym95
