### ISSUE TITLE
discoverServices throws error on IOS only during re-connection (^4.0.0) during first connection (^5.0.0) no errors (^3.0.0)

### ISSUE THREAD

**Issue by riccardocescon** [PhilipsHue/flutter_reactive_ble#411]
**Describe the bug**
This issue occurs only on IOS once you try to reconnect to a device :
The discoverServices method throws an error : 
`PlatformException(reactive_ble_mobile.Central.(unknown context at $1010530e4).Failure:2, The operation couldn’t be completed. (reactive_ble_mobile.Central.(unknown context at $1010530e4).Failure error 2.), {}, null) `

How i connect to a device :

    connectionStream = flutterReactiveBle.connectToDevice(id: address,
            servicesWithCharacteristicsToDiscover: servicesWithChars,
            connectionTimeout: const Duration(seconds: 5)).listen((event) {
              try {
                _deviceConnectionController.add(event);
              }catch(connectionError){
                print("Could not add event on closed stream!");
              }
          if (!tryingToConnect) {
            tryingToConnect = true;
            _discoverServicesAndCharacteristics(
                address, onConnectionResult, true, () {});
          }else{
            print("Cannot connect because i am already trying to connect!");
          }
        }, onError: (dynamic err) {
              print("Found error while connecting to device : ${err.toString()}");
        });
        
How i discover services: (error occurs here)

      flutterReactiveBle.discoverServices(id)
                              .onError((error, stackTrace) {
                                      print("Failed to discover services : ${error.toString()} \n ${stackTrace.toString()}");
                                      return [];
                              }).then((value) {
                                     print("received values");
                                     ....
                                     ....
                                     ....
                               });

How i disconnect from the device :

        try {
          await subscription.cancel();
          print("cancelling connection...");
          await connectionStream.cancel();
          tryingToConnect = false;
          print("not trying to connect anymore 1");
        } on Exception catch (e, _) {
          print(Error disconnecting from a device $e");
        }finally{
          if(Platform.isIOS){
            _deviceConnectionController.add(
              ConnectionStateUpdate(
                deviceId: kubeId,
                connectionState: DeviceConnectionState.disconnected,
                failure: null,
              ),
            );
          }
        }
        
So the first time i am able to connect to the device, i am able to send and receive data and i am able to disconnect from the device though only on IOS it throws this error when i try to disconnect :
`Error unsubscribing from notifications: PlatformException(reactive_ble_mobile.PluginError:7, The operation couldn’t be completed. (reactive_ble_mobile.PluginError error 7.), {}, null)`

And this may cause the discoverService to throw the other error, so i tried to re-assign the FlutterReactiveBle once disconnected but it still occurs. Then once i try to connect again it thows the error i posted before, 
`PlatformException(reactive_ble_mobile.Central.(unknown context at $1010530e4).Failure:2, The operation couldn’t be completed. (reactive_ble_mobile.Central.(unknown context at $1010530e4).Failure error 2.), {}, null) `
Stacktrace : 
`StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)

MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)

<asynchronous suspension>

FutureExtensions.onError.<anonymous closure> (dart:async/future.dart:795)

<asynchronous suspension>`

On Android it works perfectly and throws no error

Did I do something wrong, or is there an issue with IOS?

**To Reproduce**
1. Connect to one / many devices using `connectTo()` / `connectToAdvertisingDevice()`
2. Read from / write to / subscribe to a protected / non-protected characteristic
3. Disconnect from the device
4. Reconnect to the device
5. The error is thrown

**Expected behavior**
Once i try to re-connect to the device, it should work like the first time i tried to connect

**Smartphone / tablet**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 12]

**Peripheral device**
- nRF52832
- Does it run a custom firmware / software: yes

**Comment by remonh87** [comment]
which version of the library are you using?

**Comment by riccardocescon** [comment]
> which version of the library are you using?

I am using flutter_reactive_ble: ^4.0.0

**Comment by riccardocescon** [comment]
I have tried with version 5.0.1 but i get the same error

**Comment by remonh87** [comment]
I think this issue is related to: https://github.com/PhilipsHue/flutter_reactive_ble/pull/406  if I revert this commit I have no issues. I will try to fix it this weekend or else revert it

**Comment by remonh87** [comment]
Can you try this with version 5.0.2?

**Comment by riccardocescon** [comment]
I just tried with version 5.0.2 but unfortunately the same error occurs as in version 4.0.0.
The first connection is successful, the second time it does not connect and I get the error posted

**Comment by remonh87** [comment]
@riccardocescon  can you check which version of `reactive_ble_mobile` you are using (in pubhpec.lock)? because I did test it on my phone and I am able to reconnect without issues,

**Comment by riccardocescon** [comment]
> @riccardocescon can you check which version of `reactive_ble_mobile` you are using (in pubhpec.lock)? because I did test it on my phone and I am able to reconnect without issues,

Inside pubsec.lock i have:

```
flutter_reactive_ble:
    dependency: "direct main"
    description:
        name: flutter_reactive_ble
        url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.2"
```
    
```
    reactive_ble​_mobile:
    dependency: transitive
    description:
        name: flutter_reactive_ble
        url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.2"
```
    
I am pretty sure i have updated to the latest version because with v5.0.1 i couldn't connect with the first attempt, but now i can and fails with the second

**Comment by remonh87** [comment]
ow wait one thing: did you run `pod update` in your iOS folder? Sometimes cocoa pods still uses an old version (I ran into this issue today with another library). I tried it again o the example app and I have no problems at all .

**Comment by riccardocescon** [comment]
I ran the pod update command inside the ios folder again, but the issue persists

**Comment by riccardocescon** [comment]
I'm sorry to say it just now, but I just realized it. The first few times I started working with this library I noticed that on IOS had a problem starting the ble. 
`func scanForDevices(name: String, args: ScanForDevicesRequest, completion: @escaping PlatformMethodCompletionHandler) {
        guard let central = central
        else {
            completion(.failure(PluginError.notInitialized.asFlutterError))
            return
        }

        assert(!central.isScanning)

        scan = StreamingTask(parameters: .init(services: args.serviceUuids.map({ uuid in CBUUID(data: uuid.data) })))

        completion(.success(nil))
    }`

This assert was triggered so I just commented on it and carried on. Now I have removed the comment but this assert fails. 
Could this be the problem causing the other error?

File : `PluginController.swift`

**Comment by riccardocescon** [comment]
Okay I finally managed to fix the problem. 
The issue is the following: 
My problem is "special" because i am connecting with the ble to a nrf with a customized firmware, I had foreseen a command to cancel the bluetooth connection with the phone from that device. By doing this, errors were displayed on the phone because the disconnection had to be handled differently from the library example. I admit i made many attempts to find the right combination, on which stram to delete in ios and which in android, but with a little patience I managed to fix everything.

I would like to thank @remonh87 for the support and patience he has had. In case there are other problems i will re-open this issue, but as far as I'm concerned it is closed since it was my problem.

**Comment by vladms** [comment]
@riccardocescon  I am facing the same issue as you, as I am connecting  tu custom firmware. Can you tell me which was the solution for this issue? 

I have tried different solutions to cancel the streams from the ble library but none fixed the issue

**Comment by riccardocescon** [comment]
> @riccardocescon  I am facing the same issue as you, as I am connecting  tu custom firmware. Can you tell me which was the solution for this issue? 
> 
> I have tried different solutions to cancel the streams from the ble library but none fixed the issue

I rewrote the BLE functions i made.
Make sure to follow the example given with this library.
My Issue was caused by the connect/disconnect functions i wrote because i haven't followed the documentation
