### ISSUE TITLE
[CoreBluetooth] XPC connection invalid

### ISSUE THREAD

**Issue by farr64** [PhilipsHue/flutter_reactive_ble#413]
I just started noticing this every now and then:

`[CoreBluetooth] XPC connection invalid`

This message appears sporadically and perhaps this started after having upgraded to `flutter_reactive_ble v5.0.0` -- but it's possible that this message may have appeared before and I had just not noticed it.

A quick search found a few references, including 
https://github.com/NordicSemiconductor/IOS-nRF-Toolbox/issues/103

@philips77 (from Nordic Semiconductor) mentioned:

> This is just a warning. It happens when a CBCentralManager instance is disposed. In the app and in our libraries we often use one manager instance per profile to separate functionality and allow multiple delegates. iOS would prefer a singleton which lives as long as the app, but everything works as expected with multiple instances.

Anyhow, I decided to share this information in case it may be useful.

**Comment by werediver** [comment]
We use a single `CentralManager`, correct. I'm not sure how exactly our plug-in handles Flutter hot-restart, though.

**Comment by farr64** [comment]
I have kept an eye out for this warning and I haven't seen it for a few days. I do hot reloads and hot restarts all the time (both are among the greatest features that put Flutter on a very high level).

This seems to be one of those ever-elusive events that's triggered by some combination(s) of conditions. I have no idea what the triggering condition(s) might be.

Fortunately, the app works perfectly and the warning is just that: A warning.
