### ISSUE TITLE
Get List of already Connected Devices

### ISSUE THREAD

**Issue by rohitsangwan01** [PhilipsHue/flutter_reactive_ble#421]
Hey , its a great package , i just shifted from Flutter_blue to this one , but one isssue for me is ,if user kill the app directly without closing that Connection stream , the Device remain Connected to Mobile Bluetooth , but App  is killed , so when user ReOpen the App , they cant see that Device in scanned devices , or they cant connect back to that Device in App , 
in flutter_blue there is a method to get list of connected Device with bluetooth , if we can get something similar here , then it would be really great , so that when user reopen app we can simply check first if any device is already connnected , and if yes , then any way to reconnect in app or by disconnecting with it and rescan

**Comment by remonh87** [comment]
Duplicate of #322
