### ISSUE TITLE
Method to enable Bluetooth

### ISSUE THREAD

**Issue by lluisclava** [PhilipsHue/flutter_reactive_ble#426]
When you check the Bluetooth status, it will be great to have a method to enable the Bluetooth and GPS.

I tried to use diferent bluetooth plugins just to enable it, but I get some problems having two Bluetooth plugins working together.

**Comment by rohitsangwan01** [comment]
@lluisclava , if you want to show popup to the user for turning on Bluetooth and Location within the app , you can try out this package , it works for Both Android and Ios (Open device setting to turn on Bluetooth in Ios) ,
https://pub.dev/packages/grant_and_activate , 

```dart
  static Future<bool> permissionGiven() async {
    try {
      ///reomve Platform Check Condition if you wnat location on Both Platforms
      List<Feature> features = GetPlatform.isAndroid
          ? [Feature.Bluetooth, Feature.LocationWhenInUse]
          : [Feature.Bluetooth];
      Result result = await checkPermissionsAndActivateServices(features);

      if (!result.allOk) {
        // Permissions have not been granted and/or services are not active
        var isBlueActive = result.getStatus(Feature.Bluetooth);
        var isGPSActive = GetPlatform.isIOS
            ? true
            : result.getStatus(Feature.LocationWhenInUse);

        String ErroMessage = !isBlueActive && !isGPSActive
            ? 'App recquire Bluetooth and Location to work Properly'
            : !isBlueActive
                ? 'App recquire Bluetooth to work Properly'
                : 'App recquire Location to work Properly';

        //here Show an Error Popup, Change Error Messages accordingly        
        Ui.Error(ErroMessage);
      }
      return result.allOk;
    } catch (e) {
      Ui.Error(e.toString());
      return false;
    }
  }
```

Another option is , as others sujjested write native code for this , if dont want to use any other library

**Comment by remonh87** [comment]
We as maintainers had a discussion and decided to not put a method in this library. For the following reasons:

- We initialise things lazily so requesting a system dialog on iOS on initialise is not a good option
- There are a lot of other packages that solve this problem. For example the package mentioned by @rohitsangwan01 
and I personally like the https://pub.dev/packages/app_settings .

**Comment by lluisclava** [comment]
Great! Thanks for your answers and your time.

Finally I use this plugin [https://pub.dev/packages/flutter_blue_elves] just to manage the bluetooth enabling.
