### ISSUE TITLE
allowDuplicates in scanning results in duplicate connections on iOS

### ISSUE THREAD

**Issue by ajkahl** [PhilipsHue/flutter_reactive_ble#430]
### Discussed in https://github.com/PhilipsHue/flutter_reactive_ble/discussions/425

<div type='discussions-op-text'>

<sup>Originally posted by **ajkahl** October 23, 2021</sup>
Hi,

I've a device that allows a couple of concurrent connections - which are usually a combination of a phone and a keyfob remote, or maybe a couple of phones. I've recently moved my app from flutter blue and have it mostly working well, bar one issue. 

I first scan for the device, and if I come across one that has been saved (using an ID in the ad packet to avoid the iOS UUID transience) I attempt a connection, the device will then restart advertising after connecting if all of it's connections aren't used. Problem is iOS under the covers seems to claim all available connections to the device when I issue a connect, meaning that a second phone, or keyfob cannot connect. 

This doesn't seem to be an issue on Android and I've tracked it down (can only guess how iOS uses it) to CBCentralManagerScanOptionAllowDuplicatesKey being set to true (in central.swift), with it set to false the problem seems to be gone. I'm not sure of the use case of duplicates when scanning, is there a reason it's set to true in this case? It seems it's false by default and carries a battery life warning - https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerscanoptionallowduplicateskey

Cheers

Anthony</div>

**Comment by remonh87** [comment]
@werediver  can you explain why this option is set to true? My guess it is needed for RSSI / proximity?

**Comment by werediver** [comment]
The original issue sounds like the app code blindly connects to a device after every advertisement packet. This is a flaw in the application logic.

`CBCentralManagerScanOptionAllowDuplicatesKey` is set to allow the application receiving updates on every advertisement received. That may be used to filter out low RSSI devices, indeed.

While this flag is set, the app is free do deduplicate advertisement, if needed. If that flag would not be set, there would be no way for the application to continuously receive updates, on the other hand.

**Comment by ajkahl** [comment]
The assumption above is incorrect, as mentioned in the original post, once a device has been discovered, scanning is stopped, that device is then run through a full connection process, additionally it is then ignored in subsequent scans (because regardless of the _allowDups_ flag the advertising device would be seen again given I'm stopping and starting scanning around the connection activity). I can see at an application level only one connection is made using _connectToDevice_, but debug from my end device sees multiple connections made (up until the limit of concurrent connections which I have set at 2). 

So I believe we don't have full understanding of what is happening at the iOS level here, but given the problem is solved for me by leaving the setting at it's default ie. filtering on, perhaps this flag could be exposed as an optional in the _scanForDevices_ call?
