### ISSUE TITLE
canRegistry.discoveredDevices contains earlier scanned devices

### ISSUE THREAD

**Issue by ahoelzemann** [PhilipsHue/flutter_reactive_ble#456]
**Describe the bug**
scanRegistry.discoveredDevices contains earlier scanned devices after initializing a new FlutterReactiveBle instance. Which also means that it contains old manufacturerData. 

**To Reproduce**
1. Scan for devices, but don't connect.
2. Read manufacturerData
3. repeat steps 1 and 2

**Expected behavior**
discoveredDevices should only contain recently discovered devices.

**Smartphone / tablet**
iPhone X, iOS 15.0.2
Xocde 13.1

**Peripheral device**
- Bangle.js Smartwatch

**Additional context**
To solve this "problem" I now manually clear the Map stored in discoveredDevices by using `_ble.scanRegistry.discoveredDevices.clear();`
But I'm not sure if this is supposed to work like that.

**Comment by remonh87** [comment]
One of the things is that the OS sometimes  cached parts of the BLE. So it can happen that some old results show up.  I think it is the best to indeed discard unwanted results by either filtering or removing results older then X.  Your use of `clear` will clear all the results so you need to be sure that you do not have have "wanted" scan results. When you test with a device with new firmware I recommend switching BLE off, reboot phone and turn ble on.
