### ISSUE TITLE
Not able to scan for devices on ios Release

### ISSUE THREAD

**Issue by albo1337** [PhilipsHue/flutter_reactive_ble#457]
**Describe the bug**
I am not able to scan for devices on iOS 15.1 with release builds. On debug builds it works perfectly. 

**Smartphone / tablet**
iPhone XR, iOS 15.1
Xocde 13.1

**To Reproduce**
I am using the following method to scan for devices. 
```
Future _scanForDevices() async {
    Completer<DiscoveredDevice> completer = Completer();
    _flutterReactiveBle.scanForDevices(
      withServices: [
      ],
    ).listen((event) {
      showDialog(
        barrierDismissible: false,
        context: context,
        builder: (_) => VConnectAlertDialogWithTwoButtons(
          onFirstButtonPressed: () {
            Navigator.of(context).pop();
          },
          onSecondButtonPressed: () {
            Navigator.of(context).pop();
          },
          description: "FOUND DEVICE",
        ),
      );
      completer.complete(event);
    }, onError: (error) {
      completer.completeError(error);
    });
    return completer.future;
  }
```
The Dialog will never be shown on release builds. On Debug builds the dialog will be shown. I added also services and it still wont work on release builds but on debug builds it works. What am I doing wrong?

**Expected behavior**
Devices should be scanned on release builds as they are scanned on debug builds.

**Comment by remonh87** [comment]
Debug builds are a bit slower so it looks like this is a race condition. Do you make sure to check that ble is powered on ?

**Comment by albo1337** [comment]
hey @remonh87, if ble wasn't powered on, it would even work on debug builds, right? So BLE is always on, whenever I try this. Do you know something else, what I am forgetting to consider?

**Comment by albo1337** [comment]
It was indeed a race condition in one of my UI elements. Thank you very much @remonh87, I fixed it with your tip! Sorry for opening so many tickets, but I think it will help other people also, who maybe struggle with the same issues.
