### ISSUE TITLE
[Android]  Disconnect after connect

### ISSUE THREAD

**Issue by VinniciusJesus** [PhilipsHue/flutter_reactive_ble#460]
Flutter: 2.5.3
FlutterReactiveBle: 5.0.2
Samsung A10 - Android 10

When connecting to a device I am disconnected seconds later

My Log:
```
I/flutter (14223): ConnectionState for device Safer-FF35DF : DeviceConnectionState.connected
D/ViewRootImpl@8301dad[MainActivity](14223): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(14223): prepareNavigationBarInfo() DecorView@f643b71[MainActivity]
D/InputMethodManager(14223): getNavigationBarColor() -855310
D/BluetoothGatt(14223): onClientConnectionState() - status=8 clientIf=10 device=F9:D2:50:34:F3:FA
D/BluetoothGatt(14223): close()
D/BluetoothGatt(14223): unregisterApp() - mClientIf=10
I/flutter (14223): ConnectionState for device Safer-FF35DF : DeviceConnectionState.disconnected

```

My Code:
```
 flutterReactiveBle.connectToDevice(id: result.id).listen(
      (update) async {
        _deviceConnectionController.add(update);
        print(
            'ConnectionState for device ${result.name} : ${update.connectionState}');
      },
      onError: (Object e) =>
          print('Connecting to device ${model.bleName} resulted in error $e'),
    );
```

**Comment by remonh87** [comment]
Thanks for reporting. Status 8 means a `GATT_TIMEOUT` which means that the phone lost the connection with the peripheral. This is a status code reported by the bluetooth spec. There are many reasons for this to happen: incorrect synchronisation, bad antenna of the device, too many connected ble devices etc. 

This is unfortunately  not something the library can fix but my first step would be to use another phone and try to connect , connect with a ble explorer (like nrf connect ) and then check the firmware of your device.
