### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Nelmajuva** [PhilipsHue/flutter_reactive_ble#461]
Hello, when I install the flutter_reactive_ble and update the SDK version min to 21, I get the following error.

Sorry I can't provide additional information, I'm new to mobile development, I usually don't do this kind of post on github, thanks.

![Uploading Captura de pantalla 2021-11-27 171704.png…]()

**Comment by farr64** [comment]
Can't see your screen capture image. Could you please upload it again?

**Comment by Nelmajuva** [comment]
> Can't see your screen capture image. Could you please upload it again?

Hello! Fixed error (https://github.com/PhilipsHue/flutter_reactive_ble/issues/51)
Thank you very much! ^^
