### ISSUE TITLE
Stop scan for devices

### ISSUE THREAD

**Issue by Nelmajuva** [PhilipsHue/flutter_reactive_ble#462]
Hi, thank you very much for taking the time to read this.

I am using this package to connect to a watch via bluetooth and so far everything is going great.

Once I scan, I already have my device, but how once the device is detected can I stop searching for other devices?

`
_flutterReactiveBle.scanForDevices(
  withServices: [_deviceUuid],
  requireLocationServicesEnabled:  false)
    .listen((DiscoveredDevice device) {
      print(device);
  });
`

**Comment by Nelmajuva** [comment]
Additional: It is evident that it always returns the same device, but it does it indefinitely n number of times.

![image](https://user-images.githubusercontent.com/75552395/143773453-199beb6a-7cfe-429f-9159-ae7efd03c113.png)

**Comment by Nelmajuva** [comment]
Additional: The connection once made, try again.

![image](https://user-images.githubusercontent.com/75552395/143774033-257c9ba5-76d8-4281-984e-13913621ddba.png)

**Comment by Taym95** [comment]
Check [the example app ](https://github.com/PhilipsHue/flutter_reactive_ble/blob/5edf819f1f304ca7c40cc4a73ff54a733a06a9af/example/lib/src/ble/ble_scanner.dart#L50), scanForDevices returns `StreamSubscription` cancelling the  StreamSubscription. cancel() will stops the scan.
