### ISSUE TITLE
Mac OS M1 cpu build protobuf issue , I had fix it ,need update

### ISSUE THREAD

**Issue by cherho0** [PhilipsHue/flutter_reactive_ble#464]
protobuf platform error 

how to fix:
modify reactive_ble_mobile  build.gradle
protoc {

        if (project.hasProperty('protoc_platform')) {
            artifact = "com.google.protobuf:protoc:3.13.0:${protoc_platform}"
        } else {
            artifact = "com.google.protobuf:protoc:3.13.0"
        }
    }

add protoc_platform in gradle  :
open ~/.gradle
open gradle.properties
add protoc_platform=osx-x86_64   

hope update

**Comment by remonh87** [comment]
@cherho0  I think you use an older version because we solved this in #396 . This fix is released in version `5.0.1`

**Comment by cherho0** [comment]
![image](https://user-images.githubusercontent.com/9793994/144777207-ea7a16e3-6f9b-41f2-9807-c459d074c1f7.png)
I am sure it not work on may  m1 macbook , 5.0.1 and 5.0.2

**Comment by remonh87** [comment]
It looks like it is fetching the correct binary but it is not there in the repo. Indeed I checked maven.alivun and the binary is not there. I do not know if this is a specific mirror for China but I am able to build the app here on my M1

**Comment by cherho0** [comment]
It shoule be  "com.google.protobuf:protoc:3.13.0:osx-x86_64"   but not  osx-aarch_64.exe , I got your source code ,there is not the code  "osdetector.os == "osx"  here
