### ISSUE TITLE
not an issue but just a demo

### ISSUE THREAD

**Issue by sonnny** [PhilipsHue/flutter_reactive_ble#466]
Hi,
     I have been trying other flutter ble plugin, but this particular flutter_reactive_ble I have found to be most reliable. Below is the youtube demo of android controlling multi train using dcc, flutter android app is using flutter_reactive_ble, source code is in the youtube description. 

[https://www.youtube.com/watch?v=wNRwCgRMJ1g](https://www.youtube.com/watch?v=wNRwCgRMJ1g)

Thanks,
Sonny

**Comment by remonh87** [comment]
this looks really awesome!!  Thanks for sharing.

**Comment by remonh87** [comment]
btw do you have a twitter handle? I would like to share this and mention you.

**Comment by Taym95** [comment]
Great work, thanks for sharing 👏

**Comment by sonnny** [comment]
> btw do you have a twitter handle? I would like to share this and mention you.


      My twitter handle is @sonnybalut

Thanks
