### ISSUE TITLE
[Android]  Does not work on a specific device

### ISSUE THREAD

**Issue by VinniciusJesus** [PhilipsHue/flutter_reactive_ble#467]
**Cellphone 1: Iphone 7 (IOS 15.1)**
**Cellphone 2: Redmi Note 9 Pro Xiaomi (Android 11)**
**Cellphone 3: A10s Samsung (Android 10)**

**Cellphone 1** and **Cellphone 2** is work just fine!

**Cellphone 3** When connecting, it is disconnected right away. I don't know if there's anything the package can do, but I'm sharing this information in case other people are having the same problem.

All tests were with the same code.

code used below

```
  connectionSub = flutterBleInstance
        .connectToDevice(
            id: result.id, connectionTimeout: const Duration(seconds: 6))
        .listen(
      (update) async {}
```

In **Cellphone 3** pairing is suggested whenever you try to connect, other than **Cellphone 1** and **Cellphone 2**

Flutter: 2.5.3
Flutter_Reactive_ble: 5.0.2

**Comment by Taym95** [comment]
I will try to test it and get back to you, but I am afraid it is a device-specific issue!

**Comment by VinniciusJesus** [comment]
Other installed apps were trying to connect at the same time on **Cellphone 3**
