### ISSUE TITLE
Getting an error when syncing the device for a second time

### ISSUE THREAD

**Issue by kostas95** [PhilipsHue/flutter_reactive_ble#473]
Hi. I have a Beurer FT95 thermometer and I'm syncing its data to my application. If the pairing is successful between the app and the device, I'm creating a characteristic as below:

```
DiscoveredService service = services.firstWhere((element) => element.serviceId.toString().contains('1809'));
Uuid uuid35 = service.characteristicIds.firstWhereOrNull((element) => (element.toString().contains('2a1c')))!;
QualifiedCharacteristic characteristic35 = QualifiedCharacteristic(characteristicId: uuid35, serviceId: service.serviceId, deviceId: deviceId!)
```

and then I'm subscribing the characteristic as follows:

```
await Future.delayed(Duration(seconds: 1));
      char1Sub = _ble.subscribeToCharacteristic(characteristic35).listen((event) {
        print('SUB: writeCharacteristic');
        parseBpmValue(event);
      }, onError: (e) async {
        print('Error char1Sub');
        print(e);
        if (!pair) {
          Get.back();
          ToastUtils.showToast("An error with the device occured.");
        } else {
          ToastUtils.showToast("Error with the device please try again.");
          await Get.find<SensorsController>().deleteSensor(deviceId);
        }
      }, onDone: () {
        uploadState.value = LOADED;
      });
```

The first time when I'm syncing the data, everything works fine. When the process is finished, I'm trying to repeat it, but the `onError` prints the following

> Exception: GenericFailure<CharacteristicValueUpdateError>(code: CharacteristicValueUpdateError.unknown, message: "Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 19 (GATT_CONN_TERMINATE_PEER_USER)")

Can anyone explain what does this mean, am I using the library wrong? Is this a bug from the library? Thank you for your time

**Comment by remonh87** [comment]
@kostas95  GATT_CONN_TERMINATE_PEER_USER means that the peripheral resets the connection on purpose. It can be that the characteristic created doesn't support subscription. I would recommend trying with our example app or a ble explorer like nrf connect. Most likely you will experience the same behavior. There is little what our library can do about this error unfortunately.
