### ISSUE TITLE
Read RSSI from connected device

### ISSUE THREAD

**Issue by almogbrooker** [PhilipsHue/flutter_reactive_ble#474]
**Is your feature request related to a problem? (please describe)**
In my project i am using the RSSI from device and Phone for average, but I cant read the RSSI after connection.

**Describe the solution you'd like**
Read RSSI after connection.

**Additional context**
on the project Flutter_blue i found someone that wrote it **[here](https://github.com/pauldemarco/flutter_blue/pull/919/files)** .
and The project flutter_ble_lib **[here](https://pub.dev/documentation/flutter_ble_lib/latest/flutter_ble_lib/Peripheral/rssi.html)**

I need to build an app for a project I program mostly in c, so native language is not something I know or can currently get into
and your project is working perfect, better then others.
I would really really appreciate if anyone could help me with that, because at the moment only yours is working smoothly on background.

Thanks!

**Comment by Taym95** [comment]
Hi @almogbrooker , thanks for interesting the library, we are planning to add this feature, there is already an issue with that, I will close it because it is doublicate, join us on the other issues for more discussion. 

#292
