### ISSUE TITLE
Incompatible classes were found in dependencies

### ISSUE THREAD

**Issue by Princewil** [PhilipsHue/flutter_reactive_ble#480]
![16402234151117895011797475739133](https://user-images.githubusercontent.com/40724883/147174425-bbae2ac7-4d2b-4773-be99-2845171b5bae.jpg)

Pls check the above image.

**Comment by remonh87** [comment]
Make sure you use the same Kotlin version as flutter stable and this library. To bump the version in your app see: https://github.com/PhilipsHue/flutter_reactive_ble/blob/9bd6ed07672c88ea99e9e4740012f8ebc4d02f2c/example/android/build.gradle#L2

**Comment by Princewil** [comment]
Thanks alot. I work on that
