### ISSUE TITLE
android autoconnect doesn't work,  why?

### ISSUE THREAD

**Issue by compvisiondeveloper** [PhilipsHue/flutter_reactive_ble#482]
Hi,
I want to use this package instead of flutter blue ,but I can't use auto connect feature .How can i connect with which configuration?

**Comment by remonh87** [comment]
you can use auto connect when you do not specify a timeout. See: https://github.com/PhilipsHue/flutter_reactive_ble/blob/9bd6ed07672c88ea99e9e4740012f8ebc4d02f2c/packages/flutter_reactive_ble/lib/src/reactive_ble.dart#L252

**Comment by compvisiondeveloper** [comment]
Thanks for reply.
Actually i tried without a timeout but didn't work.Can you recommend any one else solution for this ?
