### ISSUE TITLE
Connect devices that support ANCS

### ISSUE THREAD

**Issue by gaogaogoo** [PhilipsHue/flutter_reactive_ble#487]
**Is your feature request related to a problem? (please describe)**
I use this project to connect a device that supports ANCS service, IOS will require the device to be paired with the system.
1. The paired device will remain connected to the system even if the APP is closed. When the app is reopened, the device cannot be searched.
2. Some users will first connect and pair with the device in the Bluetooth list of system settings. The device cannot be searched when the app is opened.

**Describe the solution you'd like**
Hope to provide devices connected by the system. Provide CBCentralManager.retrieveConnectedPeripheralsWithServices in iOS Bluetooth Library in dart.

Thank you!

**Comment by Taym95** [comment]
This goes a bit against our philosophy of not introducing platform specific methods, looks like IOS specific method.

**Comment by liang-notes** [comment]
@gaogaogoo Hi, How do you solved this issue?
