### ISSUE TITLE
Peripheral mode support

### ISSUE THREAD

**Issue by tonypottera24** [PhilipsHue/flutter_reactive_ble#49]
**Is your feature request related to a problem? (please describe)**
It would be great if peripheral mode is supported

**Comment by werediver** [comment]
Hi @tonypottera24. This is a reasonable suggestion, but after a brief consideration we tend to decline the idea of including the peripheral mode support into this library.

This library already has a decent complexity and quite some sensitive code that we need to maintain and improve. The peripheral mode implementation really deserves a separate Flutter plug-in.
