### ISSUE TITLE
flutter build appbundle fail

### ISSUE THREAD

**Issue by 0100101101001011** [PhilipsHue/flutter_reactive_ble#494]
**Describe the bug**
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':reactive_ble_mobile'.
> com.android.build.gradle.internal.api.TestVariantImpl_Decorated cannot be cast to com.android.build.gradle.internal.core.InternalBaseVariant

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**To Reproduce**
flutter build appbundle

**Smartphone / tablet**
 - Package version: 5.0.2

**Comment by remonh87** [comment]
please check:  https://github.com/PhilipsHue/flutter_reactive_ble/issues/285 . Most of the time this has to do that you are using an outdated gradle version.

Closed because duplicate.
