### ISSUE TITLE
BleStatus does not change

### ISSUE THREAD

**Issue by sonelektrikci** [PhilipsHue/flutter_reactive_ble#501]
**Describe the bug**
BleStatus does not change even I open bluetooth, location or give permission to location. On my old Huawei phone, it perfectly listen the BleStatus and change the status. However, when I try the same app on Android emulators, BleStatus does not change even if i give the location permission, open location service or open bluetooth service.

**Expected behavior**
I was expecting BleStatus to listen the changes.

**Smartphone / tablet**
 - Device: Pixel 4 API 31 (Android Emulator)
 - OS: Android 12
 - Package version: 5.0.2

**Comment by remonh87** [comment]
bluetooth does not work emulators you really need a physical device for testing this.
