### ISSUE TITLE
[iOS] API MISUSE error, because of statusStream cached value

### ISSUE THREAD

**Issue by KolesnikValentine** [PhilipsHue/flutter_reactive_ble#505]
**Describe the bug**
StatusStream emits previously cached value, which in combination with deinitialize() method call, may result in the following error on iOS devices: [CoreBluetooth] API MISUSE: <CBCentralManager: ...> can only accept this command while in the powered on state.

**Reproduction steps**
Consider the following scenario:
1. You have a page, which scans for the peripherals and it uses a bloc, which looks like this:
```
// Simplified version of the bloc
class BleBloc extends Bloc<BleBlocEvent, BleBlocState> {
  AddHubBloc({required BleClient bleClient}) 
        : _bleClient = bleClient,
        super(BleBlocState()) {
          _bleConnectedSubscription = _bluetoothRepository.statusStream.listen(
            (event) {
              if (event == BleStatus.ready) {
                 // Starting scan for devices
              }
            }
          );
  }

  // Client that exposes methods of FlutterReactiveBle
  final BleClient _bleClient;

  StreamSubscription<BluetoothStatus>? _bleConnectedSubscription;

  @override
  Future<void> close() async {
    await _bleConnectedSubscription?.cancel();
    // calls deinitialize of FlutterReactiveBle
    await _bleClient.deinitialize();
    return super.close();
  }
}
```

2. Open that page --> statusStream emits BleStatus.unknown and BleStatus.ready after some delay --> scan starts successfully.
3. Close the page --> deinitialize() is called;
4. Reopen the page --> statusStream emits BleStatus.ready right away --> scanning started and we receive [CoreBluetooth] API MISUSE: <CBCentralManager: ...> can only accept this command while in the powered on state.

**Potential solutions**
1. To not call deinitialize() when closing the bloc.
2. Modify the deinitialize() method of FlutterReactiveBle class to have:
```
_status = BleStatus.unknown;
```

Is there any potential issues if deinitialize() method is not called when we're done working with BLE?

**Smartphone / tablet**
 - Device: any iOS device
 - Package version: flutter_reactive_ble: 5.0.2

**Comment by Ilya-Vys** [comment]
Was here any good solution eventually?

**Comment by omarica** [comment]
Any update?
