### ISSUE TITLE
How to display already connected devices without reconnecting to them?

### ISSUE THREAD

**Issue by myuzkii** [PhilipsHue/flutter_reactive_ble#513]
hello there, 

i wanted to ask if it's somehow possible to display already connected devices on a page without having the need to connect to them again. I tried to find some packages or something similar but i have no luck with that. I hope some of you can help me XD
very much appreciated for some help (:

**Comment by Taym95** [comment]
When you connect to a device, you can easily store the device inside your app, the library doesn't provide API for that.
