### ISSUE TITLE
if Timed correctly Sometimes ble device connects after Canceling connection Stream

### ISSUE THREAD

**Issue by rohitsangwan01** [PhilipsHue/flutter_reactive_ble#522]
**Describe the bug**
if Timed correctly , Sometimes bluetooth device connects with the mobile just after TImeout , 

**To Reproduce**
1) Turn on device
2) Start scanning for devices
3) Turn off device that was listed
4) Click on the device that was listed, this should trigger a DISCONNECTED state due to timeout.
5) As soon as the DISCONNECTED STATE appears, turn on the device. The phone will connect to the device , but as stream Already canceled , No CONNECTED STATE will callout and app will stuck on Scanning Screen 

**Smartphone / tablet**
 - Device: [One Plus 8T]
 - OS:  [Android 11]

**Peripheral device**
- Nrf device
- Does it run a custom firmware / yes

**Additional context**
This issue Noticed in Android only , seems fine in IOS , and as it really  depends on Timing so am getting this 1/10 times 
Something same can be achieved by 
Scan for device
when our device appear in list , turn of device and Press Connect Button ( with Timeout )
and when app trying to connect to device , Hot Restart App 
and when app restarts , and start scanning , device got connected ,
seems like that connection stream not canceled , or Android still tries for connection after stream cancellation , or there might be a little delay in that

**Comment by remonh87** [comment]
Yeah this super annoying on Android. Even though send a disconnect it can still happen that the OS decides to connect to it anyway. This can even be related to the firmware implementation on the vendor. I would propose to implement a timeout for scanning and then try to call: 

https://github.com/PhilipsHue/flutter_reactive_ble/blob/8d66469df06e814a96eed48174d34525459c62c5/packages/flutter_reactive_ble/lib/src/reactive_ble.dart#L253

This should return a device stream and you can interact with it.
