### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by jicang** [PhilipsHue/flutter_reactive_ble#523]
Sometimes when I restart the app and call the `bleManager.connectToDevice(
      id: device.id,
      connectionTimeout: timeout,
    ) `
The `connectedDeviceStream` will send a connected event .
But when I then call any function that actually reads or writes data from/ to the watch  nothing happens.

**Comment by Taym95** [comment]
This seems related to #211, maybe try making the peripheral wait a bit before starting streaming data, 50–300 ms?
