### ISSUE TITLE
Issue with subscribeToCharacteristic 

### ISSUE THREAD

**Issue by abneradekz** [PhilipsHue/flutter_reactive_ble#529]
When I create a connection using the model below and cancel it, it disconnects but keeps the bluetooth active with the device, is there a way to disconnect completely? 

> final characteristic = QualifiedCharacteristic(serviceId: serviceUuid, characteristicId: characteristicUuid, deviceId: foundDeviceId);
listen = flutterReactiveBle.subscribeToCharacteristic(characteristic).listen((data) {
      // code to handle incoming data
    }, onError: (dynamic error) {
      // code to handle errors
    });
listen!.cancel();

**Comment by yuriboeira11tx** [comment]
deviceStream.cancel();

**Comment by remonh87** [comment]
which platform? Android or iOS?

**Comment by abneradekz** [comment]
Hi

I use Android, haven't started testing on iOS yet.

**Comment by abneradekz** [comment]
Hi

I set:
flutterReactiveBle.logLevel = LogLevel.verbose;

Log is:
2022-03-24 15:47:48.929 18342-18505/com.app I/flutter: sub3!.cancel()
2022-03-24 15:47:49.009 18342-18342/com.app D/BluetoothGatt: setCharacteristicNotification() - uuid: 0000fff1-0000-1000-8000-00805f9b34fb enable: false

### Image Connected to device
![WhatsApp Image 2022-03-24 at 15 50 56](https://user-images.githubusercontent.com/45203441/159989578-de717fd6-9586-4d90-9b41-d0e760d8b21e.jpeg)

### Image after use subscribe.cancel
![WhatsApp Image 2022-03-24 at 15 50 37](https://user-images.githubusercontent.com/45203441/159989581-fa08fe27-d989-49bd-b27e-eb7702fdab11.jpeg)

### Image after close app
![WhatsApp Image 2022-03-24 at 15 51 13](https://user-images.githubusercontent.com/45203441/159989585-0a9eaf70-93cc-4117-ba99-920bf8b318d4.jpeg)

You see that continue connected after use subscribe.cancel()

**Comment by cbreezier** [comment]
@abneradekz In the code you provided, you're canceling the subscription to the characteristic stream.

Where is your code to initially connect to the device? To disconnect from the device, you must cancel the stream from the `connectToDevice` API, not the stream from the `subscribeToCharacteristic` API.


```
final deviceStream = flutterReactiveBle.connectToDevice(id: deviceId);
// After this, the device is connected
deviceStream.listen((status) => {
    print(status)
});

final characteristic = QualifiedCharacteristic(serviceId: serviceUuid, characteristicId: characteristicUuid, deviceId: foundDeviceId);
listen = flutterReactiveBle.subscribeToCharacteristic(characteristic).listen((data) {
// code to handle incoming data
}, onError: (dynamic error) {
// code to handle errors
});
listen!.cancel();

// After this, the device is disconnected
await deviceStream.cancel();
```

**Comment by abneradekz** [comment]
```
final deviceStream = flutterReactiveBle.connectToDevice(id: deviceId);
// After this, the device is connected
final subscrib = deviceStream.listen((status) => {
    print(status)
});

final characteristic = QualifiedCharacteristic(serviceId: serviceUuid, characteristicId: characteristicUuid, deviceId: foundDeviceId);
listen = flutterReactiveBle.subscribeToCharacteristic(characteristic).listen((data) {
// code to handle incoming data
}, onError: (dynamic error) {
// code to handle errors
});
listen!.cancel();

// After this, the device is disconnected
await subscrib!.cancel();
```

I changed a little bit in the deviceStatus part, but it really worked that way.

Thanks

Best Regards
