### ISSUE TITLE
FlutterJNI Error When Disconnecting From a Device

### ISSUE THREAD

**Issue by yuriboeira11tx** [PhilipsHue/flutter_reactive_ble#545]
**Describe the bug**
This error is triggered as soon as the code unsubscribes with the BLE device.

**To Reproduce**
1. Connect to one device using `connectTo()`
2. Unsubscribe to a StreamSubscription canceled on device
3. Observe a failure with exception

```FlutterJNI(30640): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter_reactive_ble_connected_device. Response ID: 40```

**Smartphone / tablet**
 - Device: Samsung M62
 - OS: Android 11
 - Package version: 5.0.2

**Peripheral device**
- Vendor, model: CUSTOM
- Does it run a custom firmware: yes

**Additional context**
The context is simple, I just made a function to unsubscribe from a StreamSubscription and it worked. But an exception is generated after that. It seems to me that something was left behind. So I'm reporting something that could be a problem in the future. Thanks!

**Comment by Taym95** [comment]
I test it in example app and seems to work, I will close this issues for now
