### ISSUE TITLE
Get callback of subscribeToCharacteristic

### ISSUE THREAD

**Issue by Lexycon** [PhilipsHue/flutter_reactive_ble#553]
Hi guys,

I call the method _reactiveBle.subscribeToCharacteristic for a characteristic. And I can call handleError on that to receive errors while subscribing. But actually I can't wait for a success or a callback, right?

What I see in the log is sth. like that, but it seems to be a bluetooth debug message:
D/BluetoothGatt( 7318): setCharacteristicNotification() - uuid: 00002a01-0000-1000-8000-00805f9b34fb enable: true

Is there a chance to read this callback?

**Comment by wsmzdyss** [comment]
+1

**Comment by Taym95** [comment]
`subscribeToCharacteristic ` returns `Stream<List<int>>` just call `listen`:

``` _reactiveBle.subscribeToCharacteristic(QualifiedCharacteristic).listen((data) {
      // do your things 
    });```
