### ISSUE TITLE
BLE frames are not detected on Android 12

### ISSUE THREAD

**Issue by Przemo1418** [PhilipsHue/flutter_reactive_ble#566]
**Describe the bug**
The library detects the peripheral devices general device MAC which you can use to connect, but no BLE frames. As we noticed the issue apeared after updating Android from 11 to 12 on the Samsung S10. Works perfectly on Samsung A21S [Android 11], Huawei P30 Pro [Android 11], POCO F3 [Android 11], iOS devices.

**To Reproduce**
Using Samsung S10/S20 Plus with Android 12
1. Detect devices using
flutterReactiveBle.scanForDevices(
withServices: List.empty(), scanMode: ScanMode.lowLatency)
.listen((device){
functionToCheckIfIsOurBeacon(device)
}
2. 'Device' object does not include BLE frames (BLE services are not avaliable, though you can connect to the device using GATT and change the devices parameters)

**Expected behavior**
Should be able to detect BLE frames/services

**Smartphone / tablet**
 - Device: Samsung S10, Samsung S20 Plus
 - OS: Android 12
 - Package version: 5.0.2

**Peripheral device**
- Vendor, model: Estimote Proximity Beacon
- Does it run a custom firmware / software: no

**Additional context**
Issue is probably related to:
https://issuetracker.google.com/issues/228984309?pli=1

Screenshots of the 2 views representing the Bluetooth devices avaliable to connect and BLE frame view. On Samsung S10/S20Plus with Android 12 the BLE frame view ('Device' object) stays empty.
![BLE_Frames_View](https://user-images.githubusercontent.com/106225976/170206192-f6f4f00a-1b81-4450-a36a-91d9c269a948.jpg) ![Bluetooth_Connection_View](https://user-images.githubusercontent.com/106225976/170206193-acb2a425-e9e1-4bae-9556-600333dcf576.jpg)

**Comment by Airyzone** [comment]
I have the same problem, too.
For Android 12, iBeacon devices will not been detected. However, it works fine in Android 8 phone.

**Comment by mbabuglia** [comment]
If your Bluetooth device is a Beacon, it is probably being filtered out by Android if you are using the new permissions of Android 12:

<uses-permission android:name="android.permission.BLUETOOTH_SCAN" usesPermissionFlags="neverForLocation" />

Check [my answer on StackOverflow](https://stackoverflow.com/a/72370969/666228).

**Comment by Taym95** [comment]
@Przemo1418 can you please try this solution above?

**Comment by Przemo1418** [comment]
Unfortunately that solution doesn't work, we couldn't get the actual permissions for bluetooth to detect the beacons using that solution.

**Comment by AymenXD** [comment]
> Unfortunately that solution doesn't work, we couldn't get the actual permissions for bluetooth to detect the beacons using that solution. There was no popup nor any options in Android app settings to turn bluetooth permissions on manually.

is there a fix yet ? encountering the same problem . Can't detect any beacon !

**Comment by bufolab** [comment]
Some Android 12 are not able to detect (even using native SDK) some beacons.
One Xiamoi phone was able to see some beacons. But Pixel3 or Samsung Note 20+ did not get any beacon but could get other BLE devices. All running Android 12.

Looks like some phones are filtering these beacons.

**Comment by Przemo1418** [comment]
@Taym95 @AymenXD @bufolab 

**We managed to fix it by adding following to the manifest file:**

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.ukw_navigator"
    xmlns:tools="http://schemas.android.com/tools">
```

**and after that. lower in the file:**

```
<uses-permission android:name="android.permission.BLUETOOTH_SCAN" 
tools:remove="android:usesPermissionFlags"/>
```

**Comment by AymenXD** [comment]
Thank You so much !!!! it finally worked  I’ve been searching for a solution during the whole past month :’)  From: Przemo1418Sent: 12 July 2022 13:52To: PhilipsHue/flutter_reactive_bleCc: AymenXD; MentionSubject: Re: [PhilipsHue/flutter_reactive_ble] [Beacons] BLE frames are not detected on Android 12 (Issue ***@***.*** @AymenXD @bufolabWe managed to fix it by adding following to the manifest file:<manifest xmlns:android="http://schemas.android.com/apk/res/android"    package="com.example.ukw_navigator"    xmlns:tools="http://schemas.android.com/tools">and after that. lower in the file:<uses-permission android:name="android.permission.BLUETOOTH_SCAN" tools:remove="android:usesPermissionFlags"/>—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
