### ISSUE TITLE
Shouldn't this use Stream<Uint8List> for characteristic data?

### ISSUE THREAD

**Issue by Hackmodford** [PhilipsHue/flutter_reactive_ble#567]
**Is your feature request related to a problem? (please describe)**

Subscribing to a characteristic returns a stream of `List<int>`.

**Describe the solution you'd like**
Subscribing to a characteristic returns a stream of `Uint8List`.

**Describe alternatives you've considered**
Converting the data stream to `Uint8List` using `Uint8List.fromList()`

**Additional context**
This seems inefficient for processing byte streams. Shouldn't the stream be bytes instead of 64bit integers?

**Comment by Taym95** [comment]
repo is just a ble package, we decided to let client convert `List<int>`

**Comment by Hackmodford** [comment]
@Taym95 I'm afraid I don't understand. Could you please provide some more context?

Isn't it incredibly inefficient for 1 byte to be handled as 64 bit integers?
