### ISSUE TITLE
Can't find peripherals that implement extended advertising

### ISSUE THREAD

**Issue by BikeBr0** [PhilipsHue/flutter_reactive_ble#571]
**Describe the bug**
Since our peripheral switched to using extended advertising, I have not been able to find the peripheral when performing a scan. It was previously working when the peripheral used standard advertising. 

**To Reproduce**
1. Scan for peripherals that implement extended advertising  `_ble.scanForDevices(withServices: withServices)`

**Expected behavior**
To find the peripheral

**Smartphone / tablet**
 - Google Pixel 6 (Android 12) 
 - Google Nexus 6P (Android 8.1.0)
 - flutter_reactive_ble: ^5.0.2
 - Flutter version 3.0.1
 - Dart version 2.17.1

**Peripheral device**
- nRF52840-DK
- Does it run a custom firmware / software: yes

**Additional context**
This is an android specific bug as both advertising models work on iOS. Also, peripherals using extended advertising do appear in the scan results of the nRF Connect App on the Android Pixel 6.

**Comment by BikeBr0** [comment]
Further to the information provided above, we have tried using sample firmware provided with the nRF52840-DK and configured it to use Bluetooth 5 Advertising Extension. The peripheral shows up on nRF Connect on the Google Pixel 6 but not in my custom Flutter App. Is this not supported by flutter_reactive_ble?

**Comment by rift-labs-developer** [comment]
Im having the same problem. It seems RxAndroidBle does not support extended advertising yet (https://github.com/dariuszseweryn/RxAndroidBle/issues/774 )

**Comment by danielstuart14** [comment]
https://github.com/PhilipsHue/flutter_reactive_ble/pull/594

**Comment by danielstuart14** [comment]
@Taym95 is there any ETA for a release with the fix?

**Comment by Taym95** [comment]
@danielstuart14, I will make new release

**Comment by danielstuart14** [comment]
Any news about that?
