### ISSUE TITLE
[Question] Is this plugin no longer maintained?

### ISSUE THREAD

**Issue by pacifi5t** [PhilipsHue/flutter_reactive_ble#574]
Hello. Recently I noticed low activity in the repo. I'd like know if there's gonna be any updates to this plugin because our team use it for production in our startup. It would be a pity to change the BLE plugin again. Could you please describe the current situation about the plugin?

**Comment by Taym95** [comment]
@pacifi5t sorry for absence, this plugin will be always maintained

**Comment by pacifi5t** [comment]
Thanks, glad to hear that
