### ISSUE TITLE
Why not give me localname？

### ISSUE THREAD

**Issue by huangjian0414** [PhilipsHue/flutter_reactive_ble#580]
**Is your feature request related to a problem? (please describe)**

Why not give me localname

**Describe the solution you'd like**
Why not give me localname

**Describe alternatives you've considered**

**Additional context**
.

**Comment by huangjian0414** [comment]
There are two names. You can only give one name

**Comment by huangjian0414** [comment]
Why make this judgment？

**Comment by Taym95** [comment]
I don't get what id your problem!
