### ISSUE TITLE
Verbose logging

### ISSUE THREAD

**Issue by maBarabas** [PhilipsHue/flutter_reactive_ble#583]
There is a [logLevel](https://pub.dev/documentation/flutter_reactive_ble/latest/flutter_reactive_ble/FlutterReactiveBle/logLevel.html) field on the `FlutterReactiveBle`. After setting this to `LogLevel.verbose`, I'm not seeing any more logging in the console.

I don't see any code using the `_debugLogger` member of `FlutterReactiveBle`. I've also looked through the native android code, and there are no logs printed from there either.

This is the commit where the logging was added: https://github.com/PhilipsHue/flutter_reactive_ble/commit/29ad11fc6c414eca050b99f5eb1eeb3630af6344

It was later removed in https://github.com/PhilipsHue/flutter_reactive_ble/pull/338. The summary at the top says no functionality changed, but the debug logging was removed.

Was verbose logging meant to be removed here, or is that a mistake? If this was on purpuse, you should also remove the left over `LogLevel` and `Logger` classes.

I would like to see the data passed in and out of the native API for debugging. It looks like this old debug logging only used to print the data passed between dart and the native plugin.

**Comment by Taym95** [comment]
I think this was mistake, PR is welcome if you want to add it.
