### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by Alade5673** [PhilipsHue/flutter_reactive_ble#587]
I am getting this error when I do pub get

could not find package reactive_ble_mobile at "../packages/reactive_ble_mobile", version solving failed

and I have this already in my pubspec.yaml

dependency_overrides:
  flutter_reactive_ble:
    path: ../packages/flutter_reactive_ble
  reactive_ble_mobile:
    path: ../packages/reactive_ble_mobile

**Comment by leelai** [comment]
any update?

**Comment by sercan-uzun** [comment]
I have same problem also.

**Comment by Taym95** [comment]
You are not suppose to use:
```
reactive_ble_mobile:
path: ../packages/reactive_ble_mobile
```

use it like this:
```
flutter_reactive_ble:
path: ../packages/flutter_reactive_ble
```
