### ISSUE TITLE
Cant' run the example project

### ISSUE THREAD

**Issue by grgkro** [PhilipsHue/flutter_reactive_ble#590]
**Describe the bug**

I open the example folder in my Android Studio, run `pub get` and then run main.dart (pressing the green play button) or `flutter run` to run the example on my connected physical device (Xiaomi MI9T) or on my emulator (Google Pixel 4 with Android 26). Either way I get:

```
Launching lib\main.dart on Mi 9T in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
I/flutter (29180): Could not start Dart VM service HTTP server:
I/flutter (29180): SocketException: Failed to create server socket (OS Error: Permission denied, errno = 13), address = 127.0.0.1, port = 0
I/flutter (29180): #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:996:7)
I/flutter (29180): <asynchronous suspension>
I/flutter (29180): #1      Server.startup.startServer (dart:vmservice_io/vmservice_server.dart:424:19)
I/flutter (29180): <asynchronous suspension>
I/flutter (29180): #2      Server.startup (dart:vmservice_io/vmservice_server.dart:443:11)
I/flutter (29180): <asynchronous suspension>
```

I activated and deactivated Bluetooth, same result.

**Expected behavior**
-> Start the example app

**Smartphone / tablet**
 - Device: Xiaomi MI9T
 - OS: [Android 9]

**Comment by leelai** [comment]
any update?

**Comment by grgkro** [comment]
No still not working somehow, but it's okay, I'm still using the plugin in my project, there it works fine! Issue can be closed, at least for me, thanks!

**Comment by joelwhatever213** [comment]
Just in case some one else has the problem.
It seems that AndroidManifest.xml is missing this line:

`<uses-permission android:name="android.permission.INTERNET"/>
`

Source: https://github.com/flutter/flutter/issues/32602#issuecomment-494178777
