### ISSUE TITLE
flutter run warning 

### ISSUE THREAD

**Issue by tamaraspringer** [PhilipsHue/flutter_reactive_ble#595]
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. 

The plugin `reactive_ble_mobile` doesn't have a main class defined in C:\Users\tspringer\Documents\GitHub\flutter_reactive_ble\packages\reactive_ble_mobile\android\src\main\java\com\signify\hue\flutterreactiveble\ReactiveBlePlugin.java or C:\Users\tspringer\Documents\GitHub\flutter_reactive_ble\packages\reactive_ble_mobile\android\src\main\kotlin\com\signify\hue\flutterreactiveble\ReactiveBlePlugin.kt. This is likely to due to an incorrect `androidPackage: com.signify.hue.flutterreactiveble` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above.

**Comment by Taym95** [comment]
Please follow issues template and don't give orders
