### ISSUE TITLE
Connection with medical device

### ISSUE THREAD

**Issue by PavieOlivier** [PhilipsHue/flutter_reactive_ble#613]
Can we connect to Heath devices that support Bluetooth  << Continuous Glucose Monitoring Profile >> and read their data ?I would like to buy [this device ](https://www.freestyle.abbott/in-en/myfreestyle.html) and I need to connect to this using a custom-made app?
I am new to the domain of Bluetooth so i am quite confused 

any hint would be most appreciated

**Comment by Taym95** [comment]
Yes you can, you just need to the right characteristics and services UUIDs
