### ISSUE TITLE
Act as a Peripheral

### ISSUE THREAD

**Issue by Dennis-Do** [PhilipsHue/flutter_reactive_ble#615]
Hi,

is it possibile to act as a peripheral right now?

I am quiet new to BLE and I want to write two apps for learning purpose.
The first app acts as peripheral and sends advertisement packets and the second one acts as a central.

Unfortunately it seems there is no method to send advertisement packets.

Thank you,

Dennis

**Comment by Taym95** [comment]
No this is not possible and I we are not planning to support this.
