### ISSUE TITLE
Example app: Could not start Dart VM service HTTP server

### ISSUE THREAD

**Issue by typexy** [PhilipsHue/flutter_reactive_ble#616]
**Describe the bug**
I fetched this repository and wanted to have a look at the sample app. Unfortunately, when starting the app, the following exception is thrown:
```

I/flutter (23408): Could not start Dart VM service HTTP server:
I/flutter (23408): SocketException: Failed to create server socket (OS Error: Operation not permitted, errno = 1), address = 127.0.0.1, port = 0
I/flutter (23408): #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:996:7)
I/flutter (23408): <asynchronous suspension>
I/flutter (23408): #1      Server.startup.startServer (dart:vmservice_io/vmservice_server.dart:414:19)
I/flutter (23408): <asynchronous suspension>
I/flutter (23408): #2      Server.startup (dart:vmservice_io/vmservice_server.dart:433:11)
I/flutter (23408): <asynchronous suspension>

``` 

**To Reproduce**
1. Check out this repository
2. flutter pub get
3. run example on Android phone

**Expected behavior**
Expected the app to start

**Smartphone / tablet**
 - Device: Google Pixel 6
 - OS: Android 13
 - todays master branch

**Additional context**
To get rid of it I just added
`    <uses-permission android:name="android.permission.INTERNET"/>`
to Android manifest in the example

**Comment by Taym95** [comment]
Just add <uses-permission android:name="android.permission.INTERNET"/>, this is needed only in debug
