### ISSUE TITLE
How to handle paired devices or not

### ISSUE THREAD

**Issue by Programistich** [PhilipsHue/flutter_reactive_ble#617]
**Is your feature request related to a problem? (please describe)**
I'm always frustrated when not understand how to handle user write pair code or not

**Describe the solution you'd like**
New states for device connect - pairing/paired

**Describe alternatives you've considered**
After connect state try read some characteristic and catch if some exception

**Additional context**

**Comment by Taym95** [comment]
I dont this this is library issues, I think it is better if you ask in [stackoverflow](https://stackoverflow.com/)
