### ISSUE TITLE
Can't find already paired devices when scanning on iOS

### ISSUE THREAD

**Issue by samnbd** [PhilipsHue/flutter_reactive_ble#622]
**Describe the bug**
When scanning on iOS, the plugin is not finding devices that are already paired to the OS.

**To Reproduce**
1. Pair Pavlok device manually to the OS (iOS)
2. Start scanning using scanForDevices method 
3. none of the already Paired Pavlok device are found on scan

**Expected behavior**
The scan was suppose to find devices even if they are already paired to the iOS OS.

- We are replacing an app we have with a Flutter app, the old app is developed using Swift and it doesn't have this issue, it can find both paired and unpaired devices on scan.

**Smartphone / tablet**
 - Device: iPhone XS Max
 - OS: iOS 15.6.1
 - Package version: 5.0.2

**Peripheral device**
- Vendor, model: Pavlok 3 Device
- Does it run a custom firmware / software: yes 

**Additional context**

**Comment by Taym95** [comment]
Hi, This is expected behaviour for this library, if you already paired with device just store it somewhere.
