### ISSUE TITLE
Can't use the same characteristic UUID in 2 differents services

### ISSUE THREAD

**Issue by MoFanFr** [PhilipsHue/flutter_reactive_ble#625]
Hello,
Description:
On Android,if  there are 2 characteristics with the same uuid in 2 difference service (with the 2 different uuid), the subscribe function return the same value for the 2 characteristics.

For example:
ServiceUUID_T1 = "181A";
CharacUUID_T1 = "2A6E"
valueT1 = 10
ServiceUUID_T2 = "1815"
CharacUUID_T2 = "2A6E"
valueT2 =20

In both cases, the subcribe function give me 10. Each characteristic subscription should return their respective value: 10 and 20.

```
Future<String?> Subscribe(TextField Output, String ServiceUuid, String characteristicUuid,
      String foundDeviceId, FlutterReactiveBle ble) async {
    final characteristic = QualifiedCharacteristic(
        serviceId: Uuid.parse(ServiceUuid),
        characteristicId: Uuid.parse(characteristicUuid),
        deviceId: foundDeviceId);

    ble.subscribeToCharacteristic(characteristic).listen((data) {

      // code to handle incoming data
      setState(() {
        Output.TextValue = String.fromCharCodes(data);
        print("Value ${Output.ToString()}");
      });
    }, onError: (dynamic error) {
      // code to handle errors
    });
  }
```

My ble peripheral is a custom device but other android app (BLE scanner) can subscribe and return the correct value for each characteristic.

**Comment by Taym95** [comment]
duplicate #509
