### ISSUE TITLE
About connecting multiple devices

### ISSUE THREAD

**Issue by paintingStyle** [PhilipsHue/flutter_reactive_ble#633]
Am I doing this right, I want to be able to freely manage the connection and disconnection of each device

I can't close the connection to a specific device if I use the same stream

Or can I do it using the same subscription, I saw your code, streaming is not the way to broadcast

Looking forward to your reply, thank you

```
final _connectionStatusUpdateMap = <DeviceID, StreamSubscription<ConnectionStateUpdate>>{};

void _connectToDevice(DiscoveredDevice device)  async{
    if (_connectionStatusUpdateMap.containsKey(device.id)) {
    await _connectionStatusUpdateMap[device.id]?.cancel();
    }

    final subscription = _bluetoothService.connectToDevice(device.id).listen(
          (e) => _connectionStateUpdate(e, device),
          onError: (e) => _nofityConnectionError(e, device),
        );

    _addConnection(device, subscription);
}
```

subscribeToCharacteristic，How to deal with this? Is it the same as above?

**Comment by Taym95** [comment]
I don't think this is issues in library, better ask in https://stackoverflow.com/
