### ISSUE TITLE
Device name is empty

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [PhilipsHue/flutter_reactive_ble#639]
Hello, i was trying to use this package for BLE but i have some issues:

1) device name is emtpy (while i fetched devices with flutter_serial and got the name then I am able to see device with same id using this package)
2) I am not sure where to get ```characteristicUuid``` and ```serviceUuid``` from (i thought serviceUuid can be taken from services when devices are discovered but for this particular device services are empty)

Any help would be appriciated

**Comment by Taym95** [comment]
To get characteristics and services use `discoverServices`, I don't think this is library issues, since it works for all other devices
