### ISSUE TITLE
is there a way to retrieve service and character uuid?

### ISSUE THREAD

**Issue by vontdeux** [PhilipsHue/flutter_reactive_ble#640]
**Describe the bug**
- the device that I'm trying to connect have multiple service uuid (3), and multiple characteristic uuid(5 - 2,2 and 1 for each service respectively)

is there a way to get this uuid before i subscribe to the service?
i tried using device.serviceUuids inside scanForDevices, but it returned a wrong uuid in IOS, not even the one listed in any of the 3 service or 5 characteristic uuid)

**To Reproduce**
1. Connect to one / many devices using `connectTo()` / `connectToAdvertisingDevice()`
2. Read from / write to / subscribe to a protected / non-protected characteristic
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Expected behavior**

- [ ] I tried doing the same with a general BLE scanner application (e.g. [nRF Connect](https://duckduckgo.com/?q=nRF+connect)) and it exhibits the expected behavior as described above

**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [e.g. 1.0.0]

**Peripheral device**
- Vendor, model: [e.g. Fitbit Versa, iPhone SE, or CUSTOM]
- Does it run a custom firmware / software: yes / no

**Additional context**

**Comment by Taym95** [comment]
Use `discoverServices `
