### ISSUE TITLE
Characteristic not writeable on iOS only

### ISSUE THREAD

**Issue by thoschwa** [PhilipsHue/flutter_reactive_ble#642]
**Describe the bug**
On Android everything works fine, but on iOS when I try to write to the write characteristic I get the following exception:

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Exception: GenericFailure<WriteCharacteristicFailure>(code: WriteCharacteristicFailure.unknown, message: "The characteristic 6E400002-B5A3-F393-E0A9-E50E24DCCA9E of the service 6E400001-B5A3-F393-E0A9-E50E24DCCA9E of the peripheral B7342484-9931-4BF5-405B-35AF7C9145C3 is not writable")
#0      Result.dematerialize.<anonymous closure> (package:reactive_ble_platform_interface/src/model/result.dart:22:13)
#1      Result.iif (package:reactive_ble_platform_interface/src/model/result.dart:34:21)
#2      Result.dematerialize (package:reactive_ble_platform_interface/src/model/result.dart:15:28)
#3      ConnectedDeviceOperationImpl.writeCharacteristicWithoutResponse.<anonymous closure> (package:flutter_reactive_ble/src/connected_device_operation.dart:72:39)
<asynchronous suspension>
```

The ids are exactly the same as on Android, where everything is working as expected.
I tested it on different iOS-Versions, always the same thing.
The Ble device used is an esp32.

**Expected behavior**

- I tried doing the same with a the flutter_blue library and it worked as expected, on Android and iOS, no exception and an answer from the device as expected.

**Smartphone / tablet**
 - Device: iPhone 11, iPad Gen 6
 - OS: iOS 13, iOS 15
 - Package version: 5.0.2

**Peripheral device**
- Vendor, model: esp32
- Does it run a custom firmware / software: yes

Any help would be appreciated to figure out where this issue could be coming from.

**Comment by andrepura** [comment]
i have the same behaviour for certain characteristics.
on android everything works fine. in ios i have some trouble using writeCharacteristicWithoutResponse. 

as a workaround i'm using writeCharacteristic**With**Response on iOS

**Comment by Nolence** [comment]
This seems similar #551. I would ensure you have the write_no_response descriptor set on that characteristic in the firmware and check back here if that fixes it

**Comment by thoschwa** [comment]
@Nolence thanks a lot for the input, that was the issue.
