### ISSUE TITLE
Installing version 5.0.2 is forcing to install 5.0.3

### ISSUE THREAD

**Issue by iamsannyrai** [PhilipsHue/flutter_reactive_ble#657]
When trying to install flutter_reactive_ble with 5.0.2, version 5.0.3 is being installed.
<img width="716" alt="Screenshot 2022-12-14 at 5 02 31 PM" src="https://user-images.githubusercontent.com/50624619/207581600-b0af9eb1-bb8e-4ace-b27d-eb009eafef8c.png">

**Comment by bojidartonchev** [comment]
Remove the `^` prefix.

Example:
`flutter_reactive_ble: 5.0.2`
