### ISSUE TITLE
Question: Can I use this Library to Connect to Another Phone

### ISSUE THREAD

**Issue by cdigit** [PhilipsHue/flutter_reactive_ble#669]
Iv'e got the example app working on  Android Pixel 3a and it scans and shows several devices that I don't recognize, but I don't see the addresses of another android Pixel 3XL and iPhone right next to it. I'm not familiar with bluetooth programming, but wondering if this library is supposed to work with some other type of bluetooth  version that does not run on phones, but other devices? I do see the address for my Bose headphones, however.

**Comment by cdigit** [comment]
Closing because I did not see the discussions tab. Will post there instead.

**Comment by Taym95** [comment]
Hi, no you can not use this library to connect to another phone.
