### ISSUE TITLE
Exception: GenericFailure<ScanFailure>(code: ScanFailure.unknown, message: "Undocumented scan throttle (code 2147483646), suggested retry date is Fri Feb 17 17:17:09 GMT+08:00 2023")

### ISSUE THREAD

**Issue by wsmzdyss** [PhilipsHue/flutter_reactive_ble#691]
This problem occurs when the scan method is called frequently. I tried delaying the call again, but it still doesn't work, how can I optimize it?

**Comment by 345166018** [comment]
解决了吗？

**Comment by wsmzdyss** [comment]
没有

**Comment by BenelliFurtado** [comment]
You might wanna handle too frequent stopping and starting:

> Bluetooth scan limitations
> ... Starting from Android 7 you could not start the BLE scan more than 5 times per 30 seconds. ...

https://proandroiddev.com/android-restrictions-you-may-encounter-during-development-process-c39ede513813

**Comment by Taym95** [comment]
I wil close this issue since it is not Library issue, please check OS documentation about `Bluetooth scan limitations`
