### ISSUE TITLE
Unable to connect to my BLE device

### ISSUE THREAD

**Issue by kbessemer** [PhilipsHue/flutter_reactive_ble#694]
**Describe the bug**
I am trying to connect to a raspberry pi we have turned into a bluetooth device. My app is able to connect to another bluetooth device without any issues, and receive all services/characteristics. But when attempting to connect to our raspberry pi it is unreliable, and will only work maybe 5% of the time.

Before you blame our raspberry pi, please understand that we have used other BLE apps in the android store and we're able to connect to our raspberry pi device over bluetooth without any issues.

**To Reproduce**
1. Attempt to connect to a Raspberry Pi 4 with bluetooth enabled using bluetoothctl

**Expected behavior**
Successful connection from reactive ble plugin to raspberry pi

- [yes] I tried doing the same with a general BLE scanner application (e.g. [nRF Connect](https://duckduckgo.com/?q=nRF+connect)) and it exhibits the expected behavior as described above

**Smartphone / tablet**
 - Device: Samsung Galaxy S21 FE
 - OS: Android 12
 - Package version: ^5.0.3

**Peripheral device**
- Vendor, model: Raspberry Pi 4
- Does it run a custom firmware / software: Rasbian OS with a bluetooth simulator to setup characteristics

**Additional context**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 13.0.1 22A400 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```
void ConnectToDevice(device) async {
    setState(() {
      loading = true;
    });
    flutterReactiveBle.connectToDevice(
      id: device.id,
    ).listen((connectionState) async {
      print(connectionState);
      if (connectionState.connectionState == DeviceConnectionState.connected) {
        setState(() {
          loading = false;
          connected = true;
        });
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(
            "Connection Established",
            style: TextStyle(fontWeight: FontWeight.bold, color: Colors.black)),
            backgroundColor: Colors.grey));
        final services = await flutterReactiveBle.discoverServices(device.id);
        print(services);
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(
            "Services and Characteristics Received",
            style: TextStyle(fontWeight: FontWeight.bold, color: Colors.black)),
            backgroundColor: Colors.grey));
        Navigator.push(
            context,
            MaterialPageRoute(
                builder: (context) => ConnectionResultsView(services)));

      }
    }, onError: (Object error) {
      print(error);
      setState(() {
        loading = false;
      });
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(
          "Connection Error",
          style: TextStyle(fontWeight: FontWeight.bold, color: Colors.black)),
          backgroundColor: Colors.grey));
    });
  }
```

**Comment by ali-john** [comment]
Did you solve it? I am having a similar issue.
