### ISSUE TITLE
How can I get the hosted deviceId?

### ISSUE THREAD

**Issue by joshuamoreno1** [PhilipsHue/flutter_reactive_ble#696]
**Is your feature request related to a problem? (please describe)**
I need to get the hosted deviceId to save in my DB and relate some data.

**Describe the solution you'd like**
In stream status or in some init method I want to get in a callback or future the uuid or MAC address  from hosted device

**Describe alternatives you've considered**
Maybe this information is in device info so I can search there.

**Comment by Taym95** [comment]
We dont support this in library
