### ISSUE TITLE
Multiple characteristics with the same UUID not working?

### ISSUE THREAD

**Issue by mgeilich** [PhilipsHue/flutter_reactive_ble#702]
I have a device with 2 write buffers, denoted by 2 characteristics with the same UUID.  I created 2 characteristics with that UUID.  Writing to the first characteristic writes to the first buffer.  Writing to the second characteristic overwrites the first buffer instead of writing to the second.

Writing to two buffers this way works with native code under both Android and iOS and I am wondering what is different here?

**Comment by Taym95** [comment]
this is working now
