### ISSUE TITLE
MTU request inconsistency

### ISSUE THREAD

**Issue by pmagnuson** [PhilipsHue/flutter_reactive_ble#705]
**Describe the bug**
Trying to understand how the MTU request operates.  I have written a Flutter program which implements the Zephyr SMP protocol on a Nordic chip.  

The program performs the following MTU request and asks for 512 bytes:
```dart
 var mtu = await ble.requestMtu(deviceId: device.id, mtu: 512);
```
When I run this program against 2 different device FW versions, two different MTU results are reported which is understandable based on the configuration of the device FW.  

However, based on WireShark traces, the request from the Flutter program is different in the two cases.  
In one case the app request is 185 bytes:
![Screenshot 2023-03-12 at 4 42 48 PM](https://user-images.githubusercontent.com/1516372/224578893-9b9f1aa6-4d40-4bb3-9238-131097a34a82.png)

In another case the app request is 527 bytes:
![Screenshot 2023-03-12 at 4 31 41 PM](https://user-images.githubusercontent.com/1516372/224578927-6392652e-a1c6-4117-af5d-19687e9a1974.png)

What factors on the flutter_reactive_ble library affect the actual Bluetooth MTU request?  
What can the Flutter app do to make this request larger?  

App Device:
iPhone 7
IOS 15.4.1
flutter_reactive_ble 5.0.3

**Comment by pmagnuson** [comment]
More Information on this.  The Bluetooth device FW has been updated to provide a large MTU size of 498.  
For both Android and IOS, the following is used to request the MTU size
```dart
var mtu = await ble.requestMtu(deviceId: device.id, mtu: 512);
```
On Android, the MTU size is successfully negotiated and returns a value if 498.  
This shows the Wireshark trace where the App requests a MTU of 512, and the device responds with 498.

![Screenshot 2023-03-14 at 9 56 21 AM](https://user-images.githubusercontent.com/1516372/225066878-9839e05c-32ca-48a5-b634-412a7320224d.png)

On IOS, the same function call is used to request the MTU with the same Bluetooth device and FW.  The returned value is 182.
The Wireshark trace shows that the IOS App is issuing a Bluetooth request for 182 bytes.  This happens when the requested MTU is 512, 400, 300.  

![Screenshot 2023-03-14 at 10 00 15 AM](https://user-images.githubusercontent.com/1516372/225068067-8f614466-a359-4551-945c-89848ae8d96d.png)

What can be done to raise the requested MTU size on IOS?  
App Device:
iPhone 7
IOS 15.4.1
flutter_reactive_ble 5.0.3

**Comment by pmagnuson** [comment]
Thank you for looking at this.

**Comment by j4m3s** [comment]
No worries. I also discovered something interesting this evening:  that if you use writeWithResponse() you can send the full number of MTU bytes to the server (from an android client anyway). But if you call writeWithoutResponse() the content is truncated to MTU-3 bytes. This latter appears to be what the spec says (though I didn't know it). What's odd is that writeWithResponse() actually sends the full bytes.

Ideally I think the library would throw an exception if you try to exceed the valid payload.
