### ISSUE TITLE
unable to detect any device if any service id specified in ScanForDevices() function

### ISSUE THREAD

**Issue by MohaAmiry** [PhilipsHue/flutter_reactive_ble#712]
**Describe the bug**
if I specify `withServices` parameter in the function `scanForDevices` it will not discover any device even though i made sure the UUID is correct and discoverable.

**To Reproduce**
1. try to use ScanForDevices on an android device.

**Expected behavior**

i expect the following line to discover ALL devices with a any service that has the specified UUID.
`FlutterReactiveBle().scanForDevices(withServices: [Uuid.parse("4fafc201-1fb5-459e-8fcc-c5c9c331914b")])`

this line works and it discovers the service i need with all other available services and devices.
`FlutterReactiveBle().scanForDevices(withServices: [])`

**Tests**
- i tested my BLE via BLE two apps: LightBlue BLE and nRF Connect and the BLE device was discoverable and connectable and worked as intended.
- i also made sure that the UUID shown in both apps is identical to the UUID i'm searching for in `scanForDevices()`

**Smartphone / tablet**
 - Device: Galaxy S8
 - OS: Android 9
 - Package version: 5.0.3

**Peripheral device**
- i'm using an ESP32 microcontroller with BLE version 4.2
- ESP32 microcontroller does run on its original firmware.

**Comment by duncanmwanik** [comment]
Having the same problem, only difference is that I use Android 9 on Redmi Note 5.
@MohaAmiry Did you manage to get a solution or work-around?

**Comment by MohaAmiry** [comment]
> Having the same problem, only difference is that I use Android 9 on Redmi Note 5. @MohaAmiry Did you manage to get a solution or work-around?

not yet, I think there is something that I do not understand about advertising, because I've used other package called `flutter_blue_plus`, this package also has the same issue, but it provides an advertising status, and the advertising status of my server device (ESP32) is false, which indicates it is not discoverable.. but it is when the UUID not specified during the search. idk how this works but its ok.

so to work around this i decided to discover everything and add them to a list, then filter out the results that does not match a set of UUID i provide it.
this way i don't get results i don't need.

**Comment by MohaAmiry** [comment]
@duncanmwanik 
i've found that the problem is from ESP32 Arduino core BLE package. not from reactive BLE.
try to use a package called ESP32 NimBLE. it will work :)).
what a waste of time it was.
