### ISSUE TITLE
flutter reactive ble takes time to fetch data when sending request

### ISSUE THREAD

**Issue by adarshsinggh** [PhilipsHue/flutter_reactive_ble#713]
Whenever i am sending the request it is taking a delay of 4 seconds approximately on every step, but sometimes it works smooth in release mode

**To Reproduce**
Stream<String> manual(String deviceId) async* {
    List<int> list = [];
    final r = flutterReactiveBle.subscribeToCharacteristic(
        qualifiedChar(Uuid.parse(ServiceIds.MANUAL_BUTTON), deviceId));
    r.map((event) {
      list = event;
    });
    yield convertAscii(list);
  }

**Smartphone / tablet**
 - Device: Redmi Note 8
 - OS:  Android 10
 - Package version: latest

**Peripheral device**
- nrf nordic
- Does it run a custom firmware / software: yes

**Comment by remonh87** [comment]
This is behaviour of Ble. What happens is that aomwrimwa it takes longer. What I would recommend is using to improve this behaviour:
https://github.com/PhilipsHue/flutter_reactive_ble/blob/a8a0d6bce76dabf0cfc9a15e15bdb1a309e24ec8/packages/flutter_reactive_ble/lib/src/reactive_ble.dart#L211
