### ISSUE TITLE
UuidParsefailure parsing regular 16-bit UUID

### ISSUE THREAD

**Issue by Tobi696** [PhilipsHue/flutter_reactive_ble#715]
I get a UuidParseFailure Exception when trying to parse following uuid:
`f2e8a5f-2d69-4ff5-92e8-662756712684`

**Comment by Nolence** [comment]
The UUID should have 8-4-4-4-12 hexadecimal digits separated by hyphens but yours is 7-4-4-4-12. You can double check your uuids are correct using the nRF app or something similar (or through discovery and logging using this library).
