### ISSUE TITLE
App Closes When Trying to Disconnect

### ISSUE THREAD

**Issue by yuriboeira11tx** [PhilipsHue/flutter_reactive_ble#727]
**Describe the bug**
I'm trying to disconnect from the device, but an exception is thrown. Never appeared until now.

**To Reproduce**
1. Connect to one device using `connectTo()`
2. I disconnected from the device and got the error

**Expected behavior**
When I tried to disconnect from the device the application crashed and returned this in the console:
![image](https://user-images.githubusercontent.com/26651347/235163783-ce7ea5be-d467-4dac-8804-3072cfa5688f.png)

**Smartphone / tablet**
 - Device: Samsung M62
 - OS: Android 13
 - Package version: 5.0.3

**Comment by Ali-Ahmad-dev** [comment]
@yuriboeira11tx  This is the same issue, I am facing. Did you find any solution?

**Comment by Hari2653** [comment]
@yuriboeira11tx Same issue here also.No issue with IOS . App Crashes when Device is disconnected
Any way to reach the repo maintainer. 
Need help..

**Comment by MaxWebfactor** [comment]
Hi, you need to catch the error in the android manifest. There are similiar issues. Here is how you can solve this problem in Kotlin:
```
class MainActivity : FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine);
        RxJavaPlugins.setErrorHandler { throwable ->
            if (throwable is UndeliverableException) {
                println('!'.code * 80)
                println("Caught UndeliverableException from flutter_reactive_ble.")
                println('!'.code * 80)
                return@setErrorHandler    // ignore BleExceptions as they were surely delivered at least once
            }
            throw RuntimeException("Unexpected Throwable in RxJavaPlugins error handler", throwable)
        }
    }
}
```

**Comment by wcoder** [comment]
yes duplicated check #768
