### ISSUE TITLE
Who's the maintainer of this repo?

### ISSUE THREAD

**Issue by swift-kim** [PhilipsHue/flutter_reactive_ble#729]
https://github.com/PhilipsHue/flutter_reactive_ble/pull/688

Can I ask what I should do to get my code reviewed? The PR is now three months old.

**Comment by swift-kim** [comment]
Can I assume that this project has been abandoned?

**Comment by Taym95** [comment]
No it's not.

**Comment by swift-kim** [comment]
Hmm. Then why are all the issues and PRs completely ignored?

**Comment by bariccattion** [comment]
I'm also interested on this, since my project currently is waiting on @swift-kim PR and his work to have support for other platforms.
Is this something that we could see looking forward? What is the current state of the project?
