### ISSUE TITLE
Gatt Exception in release mode crashing the app, but not in debug mode

### ISSUE THREAD

**Issue by matanyos** [PhilipsHue/flutter_reactive_ble#735]
**Describe the bug**
when being connected and then disconnected, 
if i try to call FlutterReactiveBle().writeCharacteristicWithoutResponse
it throws a GATT Exception. which is ok.

but it causes the app to creash in release mode. in debug mode its fine the app doesnt crash.
how can i handle this exception in release mode?

**To Reproduce**
1. connect to any ble device and have a periodic task that calls FlutterReactiveBle().writeCharacteristicWithoutResponse every second with any value
2.  disconnect the device physically
3. check the exception thrown.. 

**Expected behavior**
it shouldn't crash the app. 

**Smartphone / tablet**
 - Device: Galaxy Tab A8
 - OS: [e.g. iOS 13, Android 10]

**Peripheral device**
- Vendor, model: [e.g. Fitbit Versa, iPhone SE, or CUSTOM]
- Does it run a custom firmware / software: Yes

**Additional context**

**Comment by remonh87** [comment]
I think you can fix it by doing sth like: 

try{
 FlutterReactiveBle().writeCharacteristicWithoutResponse 
on Exception catch (e){
    /// code to handle exception
}
