### ISSUE TITLE
Can't disconnect from device

### ISSUE THREAD

**Issue by bagintz** [PhilipsHue/flutter_reactive_ble#737]
If I connect to a device and then for whatever reason (hot restart, app reset, etc) lose the StreamSubscription, then I can't programmatically disconnect from the device. 

I might be missing something, but it seems like something we should be able to do...... device.disconnect() or something.

Any ideas?

**Comment by Taym95** [comment]
You disconnect when you close the connecting stream, please check example app.

**Comment by vanlooverenkoen** [comment]
I am having the same issue @bagintz just for my understanding. are you having this issue on android only? Or also on iOS?

**Comment by MaxWebfactor** [comment]
Somewhere in the description (I think) is a comment, that says that on hot restart, StreamSubscriptions are closed.

**Comment by bagintz** [comment]
@Taym95 that works unless you lose the streamsubscription (like a hot restart or some other memory event).  In that case, the BLE is still connected, but there is no programatic way (that I found) to disconnect on Android.  I haven't checked to see if it is an issue on iOS

**Comment by bradd-pktlzyer** [comment]
I am currently struggling with this same issue on iOS, the peripheral i am connecting to decides later to timeout the connection as it never receives a disconnect. I cancel the stream, which seems to not actually close/disconnect the connection.

**Comment by bagintz** [comment]
@Taym95 can you please reopen based on my and other responses?  Or suggest how to retrieve the correct stream if the object pointing to it is no longer accessible?
