### ISSUE TITLE
[ APP CRASH ISSUE FIX ] => ANDROID , WHILE DISCONNECTING FROM BLE DEVICE

### ISSUE THREAD

**Issue by Hari2653** [PhilipsHue/flutter_reactive_ble#738]
My issue related to app crash is fixed by the method below.

1. Add this line on build.gradle file
 implementation "com.polidea.rxandroidble2:rxandroidble:1.11.1"
 
2. (Important) You need to add 3 imports in mainactvity.kt file
  import io.reactivex.exceptions.UndeliverableException
  import io.reactivex.plugins.RxJavaPlugins
  import com.polidea.rxandroidble2.exceptions.BleException
  
3. Add this under Oncreate method
    RxJavaPlugins.setErrorHandler { throwable ->
            if (throwable is UndeliverableException && throwable.cause is BleException) {
                return@setErrorHandler // ignore BleExceptions since we do not have subscriber
            }
            else {
                throw throwable
            }
        }
        
   ------------------------------------------------------------------------------------
   if your app uses FlutterFragmentActivity you can add this below 
`
override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine)
super.configureFlutterEngine(flutterEngine)`      

   4. try flutter clean and run with android studio for the first time.
   
   Hope this fix your issues

**Comment by clemens-** [comment]
Thanks, that worked! Just for completeness, here is my MainActivity.kt:
```
package ch.myapp.app

import io.flutter.embedding.android.FlutterActivity
import io.reactivex.exceptions.UndeliverableException
import io.reactivex.plugins.RxJavaPlugins
import com.polidea.rxandroidble2.exceptions.BleException

import android.os.Bundle

class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        RxJavaPlugins.setErrorHandler { throwable ->
            if (throwable is UndeliverableException && throwable.cause is BleException) {
                return@setErrorHandler // ignore BleExceptions since we do not have subscriber
            } else {
                throw throwable
            }
        }
    }
}
```
