### ISSUE TITLE
Unable to scan if i provide UUID

### ISSUE THREAD

**Issue by anirudhsharma392** [PhilipsHue/flutter_reactive_ble#740]
I am unable to scan ibeacon if I provide UUID inside services, I think I am missing something. 
On the other hand, it's working fine if the empty array is provided to withServices.
here's my piece of code : 
```
    _subscription = await FlutterReactiveBle().scanForDevices(
        withServices: [Uuid.parse('11111111-1111-1111-1111-111111111111')],
        scanMode: ScanMode.lowLatency,
        requireLocationServicesEnabled:
            true).listen(onDeviceFound, onError: onError);
```
and here's the simulator screenshot :

![Screenshot_2023-05-31-22-07-01-93_a6b1ad494203a542d4dc2a6e4147b164](https://github.com/PhilipsHue/flutter_reactive_ble/assets/36081049/9e105da5-c47b-42e7-8820-2cefe1bc67e5)

**Comment by paulobikiwelu** [comment]
@anirudhsharma392 same problem with me..
With Uuid .. nothing is found 😉

**Comment by charismatest** [comment]
Same problem here, it's easier to scan without specifying services ans filter afterwards..

**Comment by meuhle** [comment]
I'm working on an app that does the same thing, but it's working for me, are u sure u're specifying the right service UUID? and not the charateristic one?

You should also provide information about your devices, Phone/Tablet and peripheral

**Comment by charismatest** [comment]
> I'm working on an app that does the same thing, but it's working for me, are u sure u're specifying the right service UUID? and not the charateristic one?
> 
> You should also provide information about your devices, Phone/Tablet and peripheral

The problem is, the device I'm working with doesn't advertise its services and I thought I could scan for the device UUID instead.

**Comment by meuhle** [comment]
@charismatest try to print ad use the device.serviceUuids that it's printed, otherwise you can check for other paramteres of the device but inside the onData function handler, there you can check for the name of the device for example

```
flutterReactiveBle.scanForDevices(
            requireLocationServicesEnabled: false,
            withServices: [serviceUuid]).listen((device) {
                 device.name == 'YOURNAME' ? //do something : //do nothing
});
```

**Comment by remonh87** [comment]
It looks like you are scanning using the device uuid on iOS. keep in mind that there is a difference between the UUID of the device (which is an iOS only generated id for the device) and the uuid of the service (which is one of the gatt services the device has).
