### ISSUE TITLE
[Android] Connection leak if cancelling connection stream happens when device is still connecting with AutoConnect on

### ISSUE THREAD

**Issue by William-Geng** [PhilipsHue/flutter_reactive_ble#745]
**Describe the bug**
cancelling subscription does not seem to cancel current connection attempt to the peripheral when cancelled during the "connecting" phase. 

**To Reproduce**
1. Connect to peripheral using ConnectToDevice without a connectionTimeout (autoConnect on)
2. Cancel the subscription to the connection stream soon after you get "connecting"
3. BluetoothGatt logs show close() called, unregisterApp() called... but soon another connect() automatically gets called as if the connection attempt is still trying and a "ghost connection" is created

**Expected behavior**
It should give up the current connection attempt the same way it would if a timeout was applied.
- [ ] I tried doing the same with a general BLE scanner application (e.g. [nRF Connect](https://duckduckgo.com/?q=nRF+connect)) and it exhibits the expected behavior as described above

**Comment by Taym95** [comment]
Duplicate  #741, I will close this and keep other issue.
