### ISSUE TITLE
Does the package supports non BLE devices ?

### ISSUE THREAD

**Issue by Tom3652** [PhilipsHue/flutter_reactive_ble#758]
I am sorry to ask a question like this, but does this package is working with non BLE devices ? The package name should speak for itself but i am not sure..

I have some devices quite old and to connect them i am using the native APIs `BluetoothManager` etc.. to connect to them. 
I could not see my device using a discovery for this package so i wonder if it's supported or not ? 

If yes then i will check to raise a real issue, otherwise you can close this :) 

Thanks for the package it works perfectly with BLE devices !

**Comment by Taym95** [comment]
This package support only BLE devices, thanks for using the library!
