### ISSUE TITLE
Using BLE connecting React native application with device asking pair pop up twice issue

### ISSUE THREAD

**Issue by SatyendraM1990** [PhilipsHue/flutter_reactive_ble#790]
**Describe the bug**
In my react native application I am using library react-native ble-plx 
Using this I am trying to connect a bluetooth enabled device with mobile application.
While paring the device system pop up is asking to pair 2 times.

**To Reproduce**
1 Once clicked on pair button in UI created that button, it will call function startScanner() will call.
Mean while switch on Bluetooth device to pair.
Immediately system pair pop will open 
select Pari a device , once we click on pair device , in center there will be one popup and click on pair, 
It should pair at that time but earlier pair a device pop not close, and asking to click on pair a device,
again I click and center pop up Pair button then pop up hide and device get pair.

**Expected behavior**

- [ ] I tried doing the same with a general BLE scanner application (e.g. [nRF Connect](https://duckduckgo.com/?q=nRF+connect)) and it exhibits the expected behavior as described above

**Smartphone / tablet**
Android 13 (Motorola)
 -

**Peripheral device**
- Vendor, model: [e.g. Fitbit Versa, iPhone SE, or CUSTOM]
- Does it run a custom firmware / software: yes / no

**Additional context**
With Iphone it's working fine, but with android version 13 I am facing this issue.
Same issue I have seen someone raise this for android 12 also

**Comment by Taym95** [comment]
How can you create a React Native issue in a Flutter package? Seriously!!
