### ISSUE TITLE
Find out if the BLE connection is encrypted

### ISSUE THREAD

**Issue by robert-virkus** [PhilipsHue/flutter_reactive_ble#805]
**Is your feature request related to a problem? (please describe)**
In my BLE connection I have to transmit sensitive data. I only want to do that when the connection is really encrypted.

**Describe the solution you'd like**
I would like to have extend the API like `DeviceConnectionState` to include the information if the connection is encrypted or not. Or maybe add another `EncryptionState` stream to have a non-breaking change instead.

**Describe alternatives you've considered**
Haven't found any.

**Additional context**
From #764  I understand that the connection will be encrypted when the connected device enforces that, however I would like to be able to detect that on the app side.

Thanks for your consideration!

**Comment by Taym95** [comment]
Ble connection is encrypted only if hardware has encrypted characteristics and OS show `pair` pop up, library can not show if connection is encrypted or not.
