### ISSUE TITLE
Conflict Between MyApplication and Flutter_reactive_blue about protobuf

### ISSUE THREAD

**Issue by weixuefeng** [PhilipsHue/flutter_reactive_ble#807]
flutter_reactive_blue use protobuf^3.18.1, and my application use protobuf^3.21.5. so i got error:
```
Duplication class com.google.protobuf.AbstractMessageLite found int modules xxxxx
```
so, i guess, if i change `implements` to `api` on [here](https://github.com/PhilipsHue/flutter_reactive_ble/blob/d07b4cdc6ddbd876a48c3bc73c24f8283fb7e40c/packages/reactive_ble_mobile/android/build.gradle#L99C15-L99C15) can make it work?

![image](https://github.com/PhilipsHue/flutter_reactive_ble/assets/25627103/28332851-53cb-435e-9176-206e2eead09c)

**Comment by nissaba** [comment]
I am having same problem, My ticked is then a dup of this..
