### ISSUE TITLE
Help filtering search results by a specific service

### ISSUE THREAD

**Issue by kbessemer** [PhilipsHue/flutter_reactive_ble#808]
I am migrating from flutter blue plus, and I am trying to filter my scan results by a service UUID. I am not sure how to convert my UUID to a List<int> for the Uuid class built into reactive ble...

Is there any good documentation for converting this?

Here is my service's id: 000018AE-0000-1000-8000-00805F9B34FB

**Comment by Taym95** [comment]
Please take look are app example
