### ISSUE TITLE
CBATTErrorDomain:10, The attribute could not be found

### ISSUE THREAD

**Issue by nguyenhuuta** [PhilipsHue/flutter_reactive_ble#813]
**Describe the bug**
Unhandled Exception: PlatformException(CBATTErrorDomain:10, The attribute could not be found., {NSLocalizedDescription: The attribute could not be found.},

**To Reproduce**
1. scanForDevices -> OK
2. connectToDevice -> OK
3. discoverAllServices -> OK
4. characteristic.subscribe -> error

**Smartphone / tablet**
 - Device: Iphone 13 Pro max
 - OS: 16.3.1
 - Package version: 5.2.0
 - flutterSdkVersion: "3.7.3"

Android still works fine, I see there is a difference between android and ios regarding UUID 
- Android 
![Android](https://github.com/PhilipsHue/flutter_reactive_ble/assets/19593249/11f9dba1-01dd-4496-885e-e5b544a3430b)

- IOS

![IOS](https://github.com/PhilipsHue/flutter_reactive_ble/assets/19593249/5c7cb434-8656-450e-aec3-85ffe65bdac8)

**Comment by Taym95** [comment]
Android publishes as Service UUID as long ID, iOS publishes as Service UUID as short ID, try this for example:

`  static const _shortUuid = "ffff";
  static const _extendedUuid = "0000ffff-0000-9999-9999-0099999999";
  static final Uuid uuid = Platform.isAndroid ? Uuid.parse(_extendedUuid) : Uuid.parse(_shortUuid);`

**Comment by nguyenhuuta** [comment]
Thanks you for reply, So what about the problem "characteristics.subscribe -> error"
