### ISSUE TITLE
Published plugin version 5.2.0 does not support federated plugin correctly

### ISSUE THREAD

**Issue by nicofossa** [PhilipsHue/flutter_reactive_ble#814]
The published version 5.2.0 on pub.dev does not support federated plugins.

I developed a federated plugin for an unsupported platform (Windows). I could not use the versione 5.2.0 from the pub.dev because it tries to initialize the Mobile plugin implementation anyway, causing a runtime error.

The related file is [packages/flutter_reactive_ble/lib/src/reactive_ble.dart](https://github.com/PhilipsHue/flutter_reactive_ble/blob/5.2.0/packages/flutter_reactive_ble/lib/src/reactive_ble.dart) line 107 in the tag 5.2.0

The custom plugin works correctly when using the master git version of the package.

This is fixed in commit d07b4cd 

Can you please publish a version supporting federated plugins? 

Thankyou

**Comment by Taym95** [comment]
We fixed CI, we will publish new version today.
