### ISSUE TITLE
Demo App for nRF52 DK UART 

### ISSUE THREAD

**Issue by AllyTechEngineering** [PhilipsHue/flutter_reactive_ble#821]
I have taken the original nRF52 DK app you reference in your Unofficial example apps
Example implementation UART over BLE section and updated it to work on an iOS iPhone. 
The repository is located at:
https://github.com/AllyTechEngineering/flutter_reactive_ble_nrf52_uart
I have not tested on an Android device yet. Feel free to use it.

**Comment by SietseAchterop** [comment]
For android, in android/app/build.gradle, set:   minSdkVersion 21
This is a requirement for reactive ble. Now works fine here, thanks!
Sietse

**Comment by Taym95** [comment]
I will close this one since it is not a library issue
