### ISSUE TITLE
The BLE app does not disconnect immediately but only after smartphone locked

### ISSUE THREAD

**Issue by ffamar** [PhilipsHue/flutter_reactive_ble#849]
Hi everyone,

Suddenly, my app, along with others like nRF Connect, doesn't disconnect from the device immediately but does so after I locked the smartphone. I don't think it's an issue with flutter_reactive_ble; rather, it seems to be a problem with my Samsung S21 Ultra. 
On other android devices, and on iOS, the issue does not occur.
However, I can't find a solution, and if this happens in the field, it could be a significant issue.

Does anyone have any suggestions?
Thank you!

**Comment by Taym95** [comment]
I will close this because this is not flutter_reactive_ble, please try to google it
