### ISSUE TITLE
Devices not paired in Android return connected with the stream ConnectionStateUpdate

### ISSUE THREAD

**Issue by Naografix** [PhilipsHue/flutter_reactive_ble#859]
Hey,

I'm encountering an issue in Android when trying to connect to a device via Bluetooth. The `ConnectionStateUpdate` reports that the connection state is "connected," but initially, the device is not paired in Android Bluetooth settings.

This poses a problem because I require a PIN to successfully pair my device, and there are several processes in place to check if my device is correctly connected or not.

How can I address this issue? One potential solution could be to modify the behavior of `scanForDevices` to return only paired devices. This way, I can ensure that I'm working with devices that are already paired and avoid connection issues that arise from the device not being properly paired beforehand.

Looking forward to your suggestions and advice on how to resolve this issue effectively.

Thanks!

**Comment by Taym95** [comment]
You can not return paired device this is not allowed in IOS
