### ISSUE TITLE
The release mode of an iOS device is opened for the first time to establish a stream with no return status

### ISSUE THREAD

**Issue by devYoungyang** [PhilipsHue/flutter_reactive_ble#864]
**Describe the bug**
The release mode of an iOS device is opened for the first time to establish a stream with no return status

**To Reproduce**
Connect a Bluetooth peripheral through deviceid and subscribe to the connection status, and no stream of the connection status is returned each time the app is opened

*

**Comment by Taym95** [comment]
please give a detailed issues, this description not helping
