### ISSUE TITLE
Bluetooth not work in Android 13

### ISSUE THREAD

**Issue by Pedro-Serer** [PhilipsHue/flutter_reactive_ble#879]
I'm called Pedro and i'm using the package flutter_reactive_ble but i'm have some problems.

The package not work in versions above the Android 12.

Firstly i had problems of permissions with the package. Then i changed my manifest file implementing the line:

![image](https://github.com/PhilipsHue/flutter_reactive_ble/assets/42715517/d8f87275-393d-4e75-9269-68e5088ce626)

The permission problem has stopped but now i have other problem. My Bluetooth start, scan but not connect... What i can make for this to work?

My function:

![image](https://github.com/PhilipsHue/flutter_reactive_ble/assets/42715517/cfc95247-4154-41e6-accd-0538e23e270f)

The application was supposed to request these permissions as soon as the APP starts

**Comment by keval-devani** [comment]
@Pedro-Serer please add BLUETOOTH_CONNECT permission in android manifest for Android API 31+.  

`<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />`

See [here](https://stackoverflow.com/a/75017408/15161717)

**Comment by Pedro-Serer** [comment]
@keval-devani these are my permissions that were already in the manifest file:
![image](https://github.com/user-attachments/assets/a7a50d77-e93b-41ad-b86a-690b1e17cf95)

**Comment by Taym95** [comment]
This is not library issue, works on Android 13 .
