### ISSUE TITLE
Require two BLE read operations to get a value from device

### ISSUE THREAD

**Issue by its-me-piyush** [PhilipsHue/flutter_reactive_ble#883]
Hi,
In my project, I'm using the `flutter_reactive_ble` package for BLE communication. I've encountered an issue where I need to perform a read operation twice to successfully get the value from a BLE device. On the first read attempt, the value returned is empty or incorrect, and only the second read provides the correct value.

**Steps to Reproduce:**

- Set up a BLE device that supports read characteristics.
- Use the flutter_reactive_ble package to initiate a read operation.
- Observe the value returned on the first read (which is incorrect or empty).
- Perform the read operation again, and observe that the correct value is returned.

**Expected Behavior:** The correct value should be returned on the first read attempt.

**Observed Behavior:** The correct value is returned only after performing the read operation twice.

**Environment:**
- flutter_reactive_ble version: 5.3.1
- Flutter version:  3.19.6
- Device: iOS 11 and iOS 15
- BLE device: raspberry pi 5

Any insight into why the first read might not work as expected would be appreciated. I am happy to provide more logs or test different configurations if needed.

**Comment by Taym95** [comment]
Did you check with nRF Connect app? it can be `raspberry pi` implementation issues, we use this library everyday and it works.

**Comment by piyushnagpal-cr8iv** [comment]
yes i tested it with nRF connect there also i have to do it twice. do you use it with raspberry pi?

**Comment by Taym95** [comment]
So this is not library issues but implementation specific issues(you raspberry pi code), yes we used it with raspberry pi.

**Comment by its-me-piyush** [comment]
can you share which library you are using in pi for ble?
