### ISSUE TITLE
How to connect multiple different devices at the same time?

### ISSUE THREAD

**Issue by yihuishou** [PhilipsHue/flutter_reactive_ble#94]
**Is your feature request related to a problem? (please describe)**
Connect multiple devices and write different information to different devices at the same time

**Describe the solution you'd like**
There is no information about multiple device connection writes in the documentation and examples

**Describe alternatives you've considered**
Nothing

**Additional context**
Nothing

**Comment by remonh87** [comment]
@yihuishou as long as you make sure you do not close the connection by terminating the stream you can connect to and execute operations on multiple devices the same way as we documented for one device. The library will make sure it handles the BLE operations like desired by the specific operating system. If you are missing something can you please elaborate more on what you would like to see in the docs?

**Comment by yihuishou** [comment]
After commenting out the content of closing the stream in the example, it is really possible to connect multiple devices with Bluetooth. Thank you 😃

**Comment by Ilya-Vys** [comment]
> After commenting out the content of closing the stream in the example, it is really possible to connect multiple devices with Bluetooth. Thank you 😃

I facing a first peripherial disconnecting when i start to searching second one with scan. Which line i have to comment?
